import type { FileToolField, FileToolResult, FileToolSpec, FileToolValues } from '../file-types.ts';
const specs:Record<string,FileToolSpec>={};const add=(x:FileToolSpec)=>specs[x.id]=x;
const file=(accept='audio/*,video/*',multiple=false,label=multiple?'Files':'Media file'):FileToolField=>({key:'file',label,type:'file',accept,multiple,required:true});
const num=(key:string,label:string,d:number,min?:number,max?:number,step=.1):FileToolField=>({key,label,type:'number',defaultValue:d,min,max,step});
const sel=(key:string,label:string,opts:{value:string;label:string}[],d?:string):FileToolField=>({key,label,type:'select',options:opts,defaultValue:d??opts[0]?.value});
const fOut=(label:string,blob:Blob,filename:string):FileToolResult=>({kind:'file',label,blob,filename,preview:blob.type.startsWith('image/')});
const one=(v:FileToolValues)=>{const f=v.file;if(!(f instanceof File)||!f.size)throw new Error('Choose a media file');return f};const many=(v:FileToolValues)=>Array.isArray(v.file)?v.file:(v.file instanceof File?[v.file]:[]);const n=(v:FileToolValues,k:string)=>Number(v[k]??0);const s=(v:FileToolValues,k:string)=>String(v[k]??'');
let ffmpegPromise:Promise<any>|undefined;
async function ffmpeg(){if(!ffmpegPromise)ffmpegPromise=(async()=>{const {FFmpeg}=await import('@ffmpeg/ffmpeg'),ff=new FFmpeg();const base=new URL('/vendor/ffmpeg/',location.origin).href;const wasmURL=(import.meta as any).env.PUBLIC_FFMPEG_WASM_URL;if(!wasmURL)throw new Error('FFmpeg WASM URL is not configured');await ff.load({coreURL:`${base}ffmpeg-core.js`,wasmURL});return ff})();return ffmpegPromise}
const ext=(f:File)=>f.name.toLowerCase().match(/\.([a-z0-9]+)$/)?.[1]||'bin';
const mime:Record<string,string>={mp3:'audio/mpeg',wav:'audio/wav',m4a:'audio/mp4',aac:'audio/aac',ogg:'audio/ogg',mp4:'video/mp4',gif:'image/gif',webm:'video/webm'};
async function transcode(f:File,args:(input:string,output:string)=>string[],outExt:string,name:string){const ff=await ffmpeg(),input=`input-${crypto.randomUUID()}.${ext(f)}`,output=`output-${crypto.randomUUID()}.${outExt}`;try{await ff.writeFile(input,new Uint8Array(await f.arrayBuffer()));const code=await ff.exec(args(input,output));if(code!==0)throw new Error('Media conversion failed');const data=await ff.readFile(output);if(typeof data==='string')throw new Error('Unexpected FFmpeg output');return fOut('Output',new Blob([data],{type:mime[outExt]??'application/octet-stream'}),name)}finally{try{await ff.deleteFile(input)}catch{}try{await ff.deleteFile(output)}catch{}}}
function conv(id:string,intro:string,accept:string,outExt:string,args:(i:string,o:string,v:FileToolValues)=>string[],fields:FileToolField[]=[]){add({id,intro,fields:[file(accept),...fields],execute:async v=>[await transcode(one(v),(i,o)=>args(i,o,v),outExt,`${id}.${outExt}`)]})}
conv('mp3-to-wav','Convert MP3 audio to WAV locally.','audio/mpeg,.mp3','wav',(i,o)=>['-i',i,'-vn','-c:a','pcm_s16le',o]);
conv('wav-to-mp3','Convert WAV audio to MP3 locally.','audio/wav,.wav','mp3',(i,o)=>['-i',i,'-vn','-c:a','libmp3lame','-q:a','2',o]);
for(const [id,accept] of [['m4a-to-mp3','audio/mp4,.m4a'],['ogg-to-mp3','audio/ogg,.ogg'],['aac-to-mp3','audio/aac,.aac']] as const)conv(id,'Convert audio to MP3 locally.',accept,'mp3',(i,o)=>['-i',i,'-vn','-c:a','libmp3lame','-q:a','2',o]);
for(const id of ['audio-trimmer','audio-cutter'])conv(id,'Trim an audio file to a selected time range.','audio/*','mp3',(i,o,v)=>['-ss',String(n(v,'start')),'-i',i,'-t',String(Math.max(.01,n(v,'duration'))),'-vn','-c:a','libmp3lame','-q:a','2',o],[num('start','Start (seconds)',0,0,86400,.1),num('duration','Duration (seconds)',10,.01,86400,.1)]);
add({id:'audio-joiner',intro:'Join multiple audio files into a single WAV file.',fields:[file('audio/*',true,'Audio files')],execute:async v=>{const fs=many(v);if(fs.length<2)throw new Error('Choose at least two audio files');const ff=await ffmpeg(),names:string[]=[];let list='';try{for(let i=0;i<fs.length;i++){const name=`join-${i}-${crypto.randomUUID()}.${ext(fs[i]!)}`;names.push(name);await ff.writeFile(name,new Uint8Array(await fs[i]!.arrayBuffer()));list+=`file '${name}'\n`}const listName=`list-${crypto.randomUUID()}.txt`,outName=`joined-${crypto.randomUUID()}.wav`;names.push(listName,outName);await ff.writeFile(listName,list);let code=await ff.exec(['-f','concat','-safe','0','-i',listName,'-c:a','pcm_s16le',outName]);if(code!==0){const args=names.filter(x=>x.startsWith('join-')).flatMap(x=>['-i',x]);const filters=fs.map((_,i)=>`[${i}:a]`).join('')+`concat=n=${fs.length}:v=0:a=1[out]`;code=await ff.exec([...args,'-filter_complex',filters,'-map','[out]','-c:a','pcm_s16le',outName])}if(code!==0)throw new Error('Audio join failed');const data=await ff.readFile(outName);if(typeof data==='string')throw new Error('Unexpected output');return[fOut('Joined audio',new Blob([data],{type:'audio/wav'}),'joined.wav')]}finally{for(const x of names)try{await ff.deleteFile(x)}catch{}}}});
conv('change-audio-volume','Change audio volume by a multiplier.','audio/*','mp3',(i,o,v)=>['-i',i,'-filter:a',`volume=${Math.max(0,n(v,'volume'))}`,'-c:a','libmp3lame','-q:a','2',o],[num('volume','Volume multiplier',1,0,10,.05)]);
conv('stereo-to-mono','Mix stereo audio down to mono.','audio/*','mp3',(i,o)=>['-i',i,'-ac','1','-c:a','libmp3lame','-q:a','2',o]);
conv('extract-audio-from-video','Extract video audio as MP3.','video/*','mp3',(i,o)=>['-i',i,'-vn','-c:a','libmp3lame','-q:a','2',o]);
conv('mp4-to-mp3','Extract MP4 audio as MP3.','video/mp4,.mp4','mp3',(i,o)=>['-i',i,'-vn','-c:a','libmp3lame','-q:a','2',o]);
conv('video-trimmer','Trim a video locally.','video/*','mp4',(i,o,v)=>['-ss',String(n(v,'start')),'-i',i,'-t',String(Math.max(.01,n(v,'duration'))),'-c:v','libx264','-c:a','aac','-movflags','+faststart',o],[num('start','Start (seconds)',0,0,86400,.1),num('duration','Duration (seconds)',10,.01,86400,.1)]);
conv('video-cropper','Crop a video to a pixel rectangle.','video/*','mp4',(i,o,v)=>['-i',i,'-vf',`crop=${Math.max(2,Math.round(n(v,'width')))}:${Math.max(2,Math.round(n(v,'height')))}:${Math.max(0,Math.round(n(v,'x')))}:${Math.max(0,Math.round(n(v,'y')))}`,'-c:v','libx264','-c:a','aac',o],[num('width','Width',720,2),num('height','Height',720,2),num('x','X',0,0),num('y','Y',0,0)]);
conv('video-rotator','Rotate a video by 90/180/270 degrees.','video/*','mp4',(i,o,v)=>{const a=s(v,'angle'),vf=a==='180'?'hflip,vflip':a==='270'?'transpose=2':'transpose=1';return['-i',i,'-vf',vf,'-c:v','libx264','-c:a','aac',o]},[sel('angle','Rotation',[{value:'90',label:'90°'},{value:'180',label:'180°'},{value:'270',label:'270°'}],'90')]);
conv('mute-video','Remove all audio tracks from a video.','video/*','mp4',(i,o)=>['-i',i,'-c:v','copy','-an',o]);
conv('gif-to-mp4','Convert an animated GIF to MP4.','image/gif,.gif','mp4',(i,o)=>['-i',i,'-movflags','faststart','-pix_fmt','yuv420p','-vf','scale=trunc(iw/2)*2:trunc(ih/2)*2','-c:v','libx264',o]);
conv('mp4-to-gif','Convert an MP4 clip to an animated GIF.','video/mp4,.mp4','gif',(i,o,v)=>['-i',i,'-vf',`fps=${Math.max(1,Math.round(n(v,'fps')))},scale=${Math.max(64,Math.round(n(v,'width')))}:-1:flags=lanczos`,o],[num('fps','FPS',12,1,30),num('width','Width',640,64,1600)]);
conv('video-speed-changer','Change video playback speed.','video/*','mp4',(i,o,v)=>{const speed=Math.max(.5,Math.min(2,n(v,'speed')));return['-i',i,'-filter_complex',`[0:v]setpts=${(1/speed).toFixed(6)}*PTS[v];[0:a]atempo=${speed}[a]`,'-map','[v]','-map','[a]','-c:v','libx264','-c:a','aac',o]},[num('speed','Speed',1,.5,2,.05)]);
conv('audio-bitrate-converter','Re-encode audio to a chosen MP3 bitrate.','audio/*','mp3',(i,o,v)=>['-i',i,'-vn','-c:a','libmp3lame','-b:a',`${Math.round(n(v,'bitrate'))}k`,o],[num('bitrate','Bitrate (kbps)',192,32,320,1)]);
conv('video-bitrate-converter','Re-encode video to a chosen video bitrate.','video/*','mp4',(i,o,v)=>['-i',i,'-c:v','libx264','-b:v',`${Math.round(n(v,'bitrate'))}k`,'-c:a','aac','-b:a','128k',o],[num('bitrate','Video bitrate (kbps)',2500,200,20000,100)]);
export const mediaFileToolIds=()=>Object.keys(specs);export const getMediaFileSpec=(id:string)=>specs[id];
