import type { FileToolResult, FileToolSpec, FileToolValues } from '../file-types.ts';
const specs:Record<string,FileToolSpec>={};const add=(x:FileToolSpec)=>specs[x.id]=x;
const file=(accept='image/*')=>({key:'file',label:'Image',type:'file' as const,accept,required:true});const one=(v:FileToolValues)=>{const f=v.file;if(!(f instanceof File)||!f.size)throw new Error('Choose a file');return f};const out=(label:string,value:string|number):FileToolResult=>({label,value,multiline:typeof value==='string'&&value.length>100});const fOut=(label:string,blob:Blob,filename:string,preview=true):FileToolResult=>({kind:'file',label,blob,filename,preview});
async function pngSquare(f:File,size=256){const b=await createImageBitmap(f),c=document.createElement('canvas');c.width=c.height=size;const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas unavailable');ctx.clearRect(0,0,size,size);const scale=Math.min(size/b.width,size/b.height),w=b.width*scale,h=b.height*scale;ctx.drawImage(b,(size-w)/2,(size-h)/2,w,h);b.close();return new Promise<Blob>((res,rej)=>c.toBlob(x=>x?res(x):rej(new Error('Encode failed')),'image/png'))}
function icoFromPng(png:Uint8Array,w=256,h=256){const head=new Uint8Array(22),dv=new DataView(head.buffer);dv.setUint16(0,0,true);dv.setUint16(2,1,true);dv.setUint16(4,1,true);head[6]=w===256?0:w;head[7]=h===256?0:h;head[8]=0;head[9]=0;dv.setUint16(10,1,true);dv.setUint16(12,32,true);dv.setUint32(14,png.length,true);dv.setUint32(18,22,true);return new Blob([head,png],{type:'image/x-icon'})}
add({id:'image-to-favicon',intro:'Create a square favicon.ico from an image.',fields:[file()],execute:async v=>{const png=await pngSquare(one(v)),ico=icoFromPng(new Uint8Array(await png.arrayBuffer()));return[fOut('Favicon',ico,'favicon.ico',false)]}});
add({id:'png-to-ico',intro:'Wrap a square PNG favicon image in an ICO container.',fields:[file('image/png,.png')],execute:async v=>{const png=await pngSquare(one(v));return[fOut('ICO file',icoFromPng(new Uint8Array(await png.arrayBuffer())),'favicon.ico',false)]}});
add({id:'ico-to-png',intro:'Render an ICO favicon to PNG using the browser decoder.',fields:[file('.ico,image/x-icon,image/vnd.microsoft.icon')],execute:async v=>[fOut('PNG image',await pngSquare(one(v)),'favicon.png')]});
add({id:'favicon-checker',intro:'Check favicon file format, dimensions and common size recommendations.',fields:[file('image/*,.ico')],execute:async v=>{const f=one(v),b=await createImageBitmap(f),w=b.width,h=b.height;b.close();return[out('Dimensions',`${w} × ${h}`),out('File size',`${(f.size/1024).toFixed(1)} KB`),out('Square',w===h?'Yes':'No'),out('Recommended',w===h&&w>=32?'Looks suitable; include 32×32/48×48/180×180 variants where needed.':'Prefer a square source of at least 32×32.') ]}});
add({id:'data-uri-to-image',intro:'Decode an image data URI to a downloadable file.',fields:[{key:'data',label:'Image data URI',type:'textarea',rows:8,placeholder:'data:image/png;base64,...'}],execute:async v=>{const value=String(v.data??'').trim(),m=value.match(/^data:([^;,]+)(;base64)?,(.*)$/s);if(!m)throw new Error('Enter a valid data URI');const mime=m[1]??'image/png',raw=m[3]??'',bytes=m[2]?Uint8Array.from(atob(raw),c=>c.charCodeAt(0)):new TextEncoder().encode(decodeURIComponent(raw)),ext=mime.split('/')[1]?.replace('jpeg','jpg')??'bin';return[fOut('Decoded image',new Blob([bytes],{type:mime}),`decoded.${ext}`)]}});
export const webAssetFileToolIds=()=>Object.keys(specs);export const getWebAssetFileSpec=(id:string)=>specs[id];
