import type { LocaleId, ToolDefinition } from '../core/types.ts';

type L<T=string> = Record<LocaleId,T>;

const categories: Record<string,L> = {
  'Calculators — Math & Everyday': {en:'Math & Everyday Calculators',es:'Calculadoras matemáticas y cotidianas','pt-BR':'Calculadoras de matemática e cotidiano',de:'Mathematik- & Alltagsrechner',fr:'Calculateurs mathématiques et quotidiens',it:'Calcolatori matematici e quotidiani',ja:'数学・日常計算ツール',ar:'حاسبات الرياضيات والحياة اليومية',id:'Kalkulator Matematika & Sehari-hari',tr:'Matematik ve Günlük Hesaplayıcılar',pl:'Kalkulatory matematyczne i codzienne',ko:'수학 및 일상 계산기',nl:'Wiskunde- en dagelijkse calculators',vi:'Máy tính toán học & hằng ngày'},
  'Calculators — Business & Finance': {en:'Business & Finance Calculators',es:'Calculadoras de negocios y finanzas','pt-BR':'Calculadoras de negócios e finanças',de:'Geschäfts- & Finanzrechner',fr:'Calculateurs business et finance',it:'Calcolatori business e finanza',ja:'ビジネス・金融計算ツール',ar:'حاسبات الأعمال والتمويل',id:'Kalkulator Bisnis & Keuangan',tr:'İş ve Finans Hesaplayıcıları',pl:'Kalkulatory biznesowe i finansowe',ko:'비즈니스 및 금융 계산기',nl:'Zakelijke en financiële calculators',vi:'Máy tính kinh doanh & tài chính'},
  'Calculators — Construction & DIY': {en:'Construction & DIY Calculators',es:'Calculadoras de construcción y bricolaje','pt-BR':'Calculadoras de construção e DIY',de:'Bau- & Heimwerkerrechner',fr:'Calculateurs construction et bricolage',it:'Calcolatori edilizia e fai da te',ja:'建築・DIY計算ツール',ar:'حاسبات البناء والأعمال اليدوية',id:'Kalkulator Konstruksi & DIY',tr:'İnşaat ve Kendin Yap Hesaplayıcıları',pl:'Kalkulatory budowlane i DIY',ko:'건축 및 DIY 계산기',nl:'Bouw- en doe-het-zelfcalculators',vi:'Máy tính xây dựng & DIY'},
  'Calculators — Photography & Creator': {en:'Photography & Creator Calculators',es:'Calculadoras de fotografía y creación','pt-BR':'Calculadoras de fotografia e criação',de:'Foto- & Creator-Rechner',fr:'Calculateurs photo et création',it:'Calcolatori fotografia e creator',ja:'写真・クリエイター計算ツール',ar:'حاسبات التصوير وصناعة المحتوى',id:'Kalkulator Fotografi & Kreator',tr:'Fotoğraf ve İçerik Üretici Hesaplayıcıları',pl:'Kalkulatory fotograficzne i twórców',ko:'사진 및 크리에이터 계산기',nl:'Fotografie- en creatorcalculators',vi:'Máy tính nhiếp ảnh & sáng tạo'},
  'Text Tools': {en:'Text Tools',es:'Herramientas de texto','pt-BR':'Ferramentas de texto',de:'Textwerkzeuge',fr:'Outils de texte',it:'Strumenti di testo',ja:'テキストツール',ar:'أدوات النص',id:'Alat Teks',tr:'Metin Araçları',pl:'Narzędzia tekstowe',ko:'텍스트 도구',nl:'Teksttools',vi:'Công cụ văn bản'},
  'Developer & Data Tools': {en:'Developer & Data Tools',es:'Herramientas para desarrolladores y datos','pt-BR':'Ferramentas para desenvolvedores e dados',de:'Entwickler- & Datenwerkzeuge',fr:'Outils développeur et données',it:'Strumenti sviluppatore e dati',ja:'開発者・データツール',ar:'أدوات المطورين والبيانات',id:'Alat Pengembang & Data',tr:'Geliştirici ve Veri Araçları',pl:'Narzędzia deweloperskie i danych',ko:'개발자 및 데이터 도구',nl:'Developer- en datatools',vi:'Công cụ lập trình & dữ liệu'},
  'Encoding, Hash & ID Tools': {en:'Encoding, Hash & ID Tools',es:'Herramientas de codificación, hash e ID','pt-BR':'Ferramentas de codificação, hash e ID',de:'Kodierungs-, Hash- & ID-Tools',fr:'Outils encodage, hash et identifiants',it:'Strumenti codifica, hash e ID',ja:'エンコード・ハッシュ・IDツール',ar:'أدوات الترميز والتجزئة والمعرّفات',id:'Alat Encoding, Hash & ID',tr:'Kodlama, Hash ve Kimlik Araçları',pl:'Narzędzia kodowania, hash i ID',ko:'인코딩, 해시 및 ID 도구',nl:'Encoding-, hash- en ID-tools',vi:'Công cụ mã hóa, hash & ID'},
  'Random & Picker Tools': {en:'Random & Picker Tools',es:'Herramientas aleatorias y selectores','pt-BR':'Ferramentas aleatórias e seletores',de:'Zufalls- & Auswahlwerkzeuge',fr:'Outils aléatoires et sélecteurs',it:'Strumenti casuali e selettori',ja:'ランダム・抽選ツール',ar:'أدوات عشوائية واختيار',id:'Alat Acak & Pemilih',tr:'Rastgele ve Seçim Araçları',pl:'Narzędzia losowe i selektory',ko:'랜덤 및 선택 도구',nl:'Willekeurige en keuzetools',vi:'Công cụ ngẫu nhiên & chọn lựa'},
  'Color & Design Tools': {en:'Color & Design Tools',es:'Herramientas de color y diseño','pt-BR':'Ferramentas de cor e design',de:'Farb- & Designwerkzeuge',fr:'Outils couleur et design',it:'Strumenti colore e design',ja:'カラー・デザインツール',ar:'أدوات الألوان والتصميم',id:'Alat Warna & Desain',tr:'Renk ve Tasarım Araçları',pl:'Narzędzia kolorów i projektowania',ko:'색상 및 디자인 도구',nl:'Kleur- en designtools',vi:'Công cụ màu sắc & thiết kế'},
  'Image Tools': {en:'Image Tools',es:'Herramientas de imagen','pt-BR':'Ferramentas de imagem',de:'Bildwerkzeuge',fr:'Outils image',it:'Strumenti immagini',ja:'画像ツール',ar:'أدوات الصور',id:'Alat Gambar',tr:'Görsel Araçları',pl:'Narzędzia obrazów',ko:'이미지 도구',nl:'Afbeeldingstools',vi:'Công cụ hình ảnh'},
  'Web Asset Tools': {en:'Web Asset Tools',es:'Herramientas para recursos web','pt-BR':'Ferramentas de recursos web',de:'Web-Asset-Werkzeuge',fr:'Outils de ressources web',it:'Strumenti asset web',ja:'Webアセットツール',ar:'أدوات أصول الويب',id:'Alat Aset Web',tr:'Web Varlık Araçları',pl:'Narzędzia zasobów web',ko:'웹 에셋 도구',nl:'Webassett-tools',vi:'Công cụ tài nguyên web'},
  'QR & Barcode Tools': {en:'QR & Barcode Tools',es:'Herramientas QR y códigos de barras','pt-BR':'Ferramentas QR e código de barras',de:'QR- & Barcode-Werkzeuge',fr:'Outils QR et codes-barres',it:'Strumenti QR e codici a barre',ja:'QR・バーコードツール',ar:'أدوات QR والباركود',id:'Alat QR & Barcode',tr:'QR ve Barkod Araçları',pl:'Narzędzia QR i kodów kreskowych',ko:'QR 및 바코드 도구',nl:'QR- en barcodetools',vi:'Công cụ QR & mã vạch'},
  'PDF Tools': {en:'PDF Tools',es:'Herramientas PDF','pt-BR':'Ferramentas PDF',de:'PDF-Werkzeuge',fr:'Outils PDF',it:'Strumenti PDF',ja:'PDFツール',ar:'أدوات PDF',id:'Alat PDF',tr:'PDF Araçları',pl:'Narzędzia PDF',ko:'PDF 도구',nl:'PDF-tools',vi:'Công cụ PDF'},
  'Audio, Video & Subtitle Tools': {en:'Audio, Video & Subtitle Tools',es:'Herramientas de audio, vídeo y subtítulos','pt-BR':'Ferramentas de áudio, vídeo e legendas',de:'Audio-, Video- & Untertitelwerkzeuge',fr:'Outils audio, vidéo et sous-titres',it:'Strumenti audio, video e sottotitoli',ja:'音声・動画・字幕ツール',ar:'أدوات الصوت والفيديو والترجمة',id:'Alat Audio, Video & Subtitle',tr:'Ses, Video ve Altyazı Araçları',pl:'Narzędzia audio, wideo i napisów',ko:'오디오, 비디오 및 자막 도구',nl:'Audio-, video- en ondertiteltools',vi:'Công cụ âm thanh, video & phụ đề'},
  '3D Printing & Maker Tools': {en:'3D Printing & Maker Tools',es:'Herramientas de impresión 3D y maker','pt-BR':'Ferramentas de impressão 3D e maker',de:'3D-Druck- & Maker-Werkzeuge',fr:'Outils impression 3D et maker',it:'Strumenti stampa 3D e maker',ja:'3Dプリント・メイカーツール',ar:'أدوات الطباعة ثلاثية الأبعاد والصنّاع',id:'Alat 3D Printing & Maker',tr:'3D Baskı ve Maker Araçları',pl:'Narzędzia druku 3D i maker',ko:'3D 프린팅 및 메이커 도구',nl:'3D-print- en makertools',vi:'Công cụ in 3D & maker'},
  'Unit & Technical Converters': {en:'Unit & Technical Converters',es:'Conversores de unidades y técnicos','pt-BR':'Conversores de unidades e técnicos',de:'Einheiten- & Technik-Konverter',fr:'Convertisseurs d’unités et techniques',it:'Convertitori di unità e tecnici',ja:'単位・技術変換ツール',ar:'محولات الوحدات والتقنية',id:'Konverter Unit & Teknis',tr:'Birim ve Teknik Dönüştürücüler',pl:'Konwertery jednostek i techniczne',ko:'단위 및 기술 변환기',nl:'Eenheden- en technische converters',vi:'Bộ chuyển đổi đơn vị & kỹ thuật'},
};

const types: Record<string,L> = {
  Calculator:{en:'Calculator',es:'Calculadora','pt-BR':'Calculadora',de:'Rechner',fr:'Calculateur',it:'Calcolatore',ja:'計算機',ar:'حاسبة',id:'Kalkulator',tr:'Hesaplayıcı',pl:'Kalkulator',ko:'계산기',nl:'Calculator',vi:'Máy tính'},
  Generator:{en:'Generator',es:'Generador','pt-BR':'Gerador',de:'Generator',fr:'Générateur',it:'Generatore',ja:'ジェネレーター',ar:'مولد',id:'Generator',tr:'Üreteç',pl:'Generator',ko:'생성기',nl:'Generator',vi:'Trình tạo'},
  Converter:{en:'Converter',es:'Convertidor','pt-BR':'Conversor',de:'Konverter',fr:'Convertisseur',it:'Convertitore',ja:'コンバーター',ar:'محول',id:'Konverter',tr:'Dönüştürücü',pl:'Konwerter',ko:'변환기',nl:'Converter',vi:'Bộ chuyển đổi'},
  Checker:{en:'Checker',es:'Verificador','pt-BR':'Verificador',de:'Prüfer',fr:'Vérificateur',it:'Verificatore',ja:'チェッカー',ar:'مدقق',id:'Pemeriksa',tr:'Kontrol Aracı',pl:'Sprawdzarka',ko:'검사기',nl:'Checker',vi:'Trình kiểm tra'},
  Counter:{en:'Counter',es:'Contador','pt-BR':'Contador',de:'Zähler',fr:'Compteur',it:'Contatore',ja:'カウンター',ar:'عداد',id:'Penghitung',tr:'Sayaç',pl:'Licznik',ko:'카운터',nl:'Teller',vi:'Bộ đếm'},
  Viewer:{en:'Viewer',es:'Visor','pt-BR':'Visualizador',de:'Betrachter',fr:'Visionneuse',it:'Visualizzatore',ja:'ビューア',ar:'عارض',id:'Penampil',tr:'Görüntüleyici',pl:'Podgląd',ko:'뷰어',nl:'Viewer',vi:'Trình xem'},
  Reader:{en:'Reader',es:'Lector','pt-BR':'Leitor',de:'Leser',fr:'Lecteur',it:'Lettore',ja:'リーダー',ar:'قارئ',id:'Pembaca',tr:'Okuyucu',pl:'Czytnik',ko:'리더',nl:'Lezer',vi:'Trình đọc'},
  Formatter:{en:'Formatter',es:'Formateador','pt-BR':'Formatador',de:'Formatierer',fr:'Formateur',it:'Formattatore',ja:'フォーマッター',ar:'منسق',id:'Pemformat',tr:'Biçimlendirici',pl:'Formater',ko:'포매터',nl:'Formatter',vi:'Trình định dạng'},
  Validator:{en:'Validator',es:'Validador','pt-BR':'Validador',de:'Validator',fr:'Validateur',it:'Validatore',ja:'バリデーター',ar:'مدقق',id:'Validator',tr:'Doğrulayıcı',pl:'Walidator',ko:'검증기',nl:'Validator',vi:'Trình xác thực'},
  Encoder:{en:'Encoder',es:'Codificador','pt-BR':'Codificador',de:'Encoder',fr:'Encodeur',it:'Codificatore',ja:'エンコーダー',ar:'مُرمّز',id:'Encoder',tr:'Kodlayıcı',pl:'Koder',ko:'인코더',nl:'Encoder',vi:'Bộ mã hóa'},
  Decoder:{en:'Decoder',es:'Decodificador','pt-BR':'Decodificador',de:'Decoder',fr:'Décodeur',it:'Decodificatore',ja:'デコーダー',ar:'مفكك ترميز',id:'Decoder',tr:'Kod Çözücü',pl:'Dekoder',ko:'디코더',nl:'Decoder',vi:'Bộ giải mã'},
  Parser:{en:'Parser',es:'Analizador','pt-BR':'Parser',de:'Parser',fr:'Analyseur',it:'Parser',ja:'パーサー',ar:'محلل',id:'Parser',tr:'Ayrıştırıcı',pl:'Parser',ko:'파서',nl:'Parser',vi:'Trình phân tích'},
  Resizer:{en:'Resizer',es:'Redimensionador','pt-BR':'Redimensionador',de:'Größenänderer',fr:'Redimensionneur',it:'Ridimensionatore',ja:'リサイズ',ar:'مغير الحجم',id:'Pengubah Ukuran',tr:'Boyutlandırıcı',pl:'Zmiana rozmiaru',ko:'크기 조절기',nl:'Formaatwijziger',vi:'Trình đổi kích thước'},
  Extractor:{en:'Extractor',es:'Extractor','pt-BR':'Extrator',de:'Extraktor',fr:'Extracteur',it:'Estrattore',ja:'抽出ツール',ar:'مستخرج',id:'Ekstraktor',tr:'Çıkarıcı',pl:'Ekstraktor',ko:'추출기',nl:'Extractor',vi:'Trình trích xuất'},
  Analyzer:{en:'Analyzer',es:'Analizador','pt-BR':'Analisador',de:'Analysator',fr:'Analyseur',it:'Analizzatore',ja:'分析ツール',ar:'محلل',id:'Penganalisis',tr:'Analiz Aracı',pl:'Analizator',ko:'분석기',nl:'Analysator',vi:'Trình phân tích'},
  Picker:{en:'Picker',es:'Selector','pt-BR':'Seletor',de:'Auswahl',fr:'Sélecteur',it:'Selettore',ja:'選択ツール',ar:'منتقي',id:'Pemilih',tr:'Seçici',pl:'Selektor',ko:'선택기',nl:'Kiezer',vi:'Bộ chọn'},
};

const words: Record<string,L> = {
  Percentage:{en:'Percentage',es:'Porcentaje','pt-BR':'Porcentagem',de:'Prozent',fr:'Pourcentage',it:'Percentuale',ja:'パーセンテージ',ar:'النسبة المئوية',id:'Persentase',tr:'Yüzde',pl:'Procent',ko:'백분율',nl:'Percentage',vi:'Phần trăm'},
  Image:{en:'Image',es:'Imagen','pt-BR':'Imagem',de:'Bild',fr:'Image',it:'Immagine',ja:'画像',ar:'الصورة',id:'Gambar',tr:'Görsel',pl:'Obraz',ko:'이미지',nl:'Afbeelding',vi:'Hình ảnh'},
  Text:{en:'Text',es:'Texto','pt-BR':'Texto',de:'Text',fr:'Texte',it:'Testo',ja:'テキスト',ar:'النص',id:'Teks',tr:'Metin',pl:'Tekst',ko:'텍스트',nl:'Tekst',vi:'Văn bản'},
  Color:{en:'Color',es:'Color','pt-BR':'Cor',de:'Farbe',fr:'Couleur',it:'Colore',ja:'色',ar:'اللون',id:'Warna',tr:'Renk',pl:'Kolor',ko:'색상',nl:'Kleur',vi:'Màu'},
  Random:{en:'Random',es:'Aleatorio','pt-BR':'Aleatório',de:'Zufalls',fr:'Aléatoire',it:'Casuale',ja:'ランダム',ar:'عشوائي',id:'Acak',tr:'Rastgele',pl:'Losowy',ko:'랜덤',nl:'Willekeurig',vi:'Ngẫu nhiên'},
  Number:{en:'Number',es:'Número','pt-BR':'Número',de:'Zahl',fr:'Nombre',it:'Numero',ja:'数値',ar:'الرقم',id:'Angka',tr:'Sayı',pl:'Liczba',ko:'숫자',nl:'Getal',vi:'Số'},
  Word:{en:'Word',es:'Palabras','pt-BR':'Palavras',de:'Wörter',fr:'Mots',it:'Parole',ja:'単語',ar:'الكلمات',id:'Kata',tr:'Kelime',pl:'Słów',ko:'단어',nl:'Woorden',vi:'Từ'},
  Character:{en:'Character',es:'Caracteres','pt-BR':'Caracteres',de:'Zeichen',fr:'Caractères',it:'Caratteri',ja:'文字',ar:'الأحرف',id:'Karakter',tr:'Karakter',pl:'Znaków',ko:'문자',nl:'Tekens',vi:'Ký tự'},
  Time:{en:'Time',es:'Tiempo','pt-BR':'Tempo',de:'Zeit',fr:'Temps',it:'Tempo',ja:'時間',ar:'الوقت',id:'Waktu',tr:'Zaman',pl:'Czas',ko:'시간',nl:'Tijd',vi:'Thời gian'},
  Date:{en:'Date',es:'Fecha','pt-BR':'Data',de:'Datum',fr:'Date',it:'Data',ja:'日付',ar:'التاريخ',id:'Tanggal',tr:'Tarih',pl:'Data',ko:'날짜',nl:'Datum',vi:'Ngày'},
  File:{en:'File',es:'Archivo','pt-BR':'Arquivo',de:'Datei',fr:'Fichier',it:'File',ja:'ファイル',ar:'الملف',id:'File',tr:'Dosya',pl:'Plik',ko:'파일',nl:'Bestand',vi:'Tệp'},
  Size:{en:'Size',es:'Tamaño','pt-BR':'Tamanho',de:'Größe',fr:'Taille',it:'Dimensione',ja:'サイズ',ar:'الحجم',id:'Ukuran',tr:'Boyut',pl:'Rozmiar',ko:'크기',nl:'Grootte',vi:'Kích thước'},
  Volume:{en:'Volume',es:'Volumen','pt-BR':'Volume',de:'Volumen',fr:'Volume',it:'Volume',ja:'体積',ar:'الحجم',id:'Volume',tr:'Hacim',pl:'Objętość',ko:'부피',nl:'Volume',vi:'Thể tích'},
  Area:{en:'Area',es:'Área','pt-BR':'Área',de:'Fläche',fr:'Surface',it:'Area',ja:'面積',ar:'المساحة',id:'Luas',tr:'Alan',pl:'Powierzchnia',ko:'면적',nl:'Oppervlakte',vi:'Diện tích'},
  Length:{en:'Length',es:'Longitud','pt-BR':'Comprimento',de:'Länge',fr:'Longueur',it:'Lunghezza',ja:'長さ',ar:'الطول',id:'Panjang',tr:'Uzunluk',pl:'Długość',ko:'길이',nl:'Lengte',vi:'Chiều dài'},
  Weight:{en:'Weight',es:'Peso','pt-BR':'Peso',de:'Gewicht',fr:'Poids',it:'Peso',ja:'重量',ar:'الوزن',id:'Berat',tr:'Ağırlık',pl:'Waga',ko:'무게',nl:'Gewicht',vi:'Trọng lượng'},
  Temperature:{en:'Temperature',es:'Temperatura','pt-BR':'Temperatura',de:'Temperatur',fr:'Température',it:'Temperatura',ja:'温度',ar:'درجة الحرارة',id:'Suhu',tr:'Sıcaklık',pl:'Temperatura',ko:'온도',nl:'Temperatuur',vi:'Nhiệt độ'},
  Speed:{en:'Speed',es:'Velocidad','pt-BR':'Velocidade',de:'Geschwindigkeit',fr:'Vitesse',it:'Velocità',ja:'速度',ar:'السرعة',id:'Kecepatan',tr:'Hız',pl:'Prędkość',ko:'속도',nl:'Snelheid',vi:'Tốc độ'},
  Password:{en:'Password',es:'Contraseña','pt-BR':'Senha',de:'Passwort',fr:'Mot de passe',it:'Password',ja:'パスワード',ar:'كلمة المرور',id:'Kata Sandi',tr:'Parola',pl:'Hasło',ko:'비밀번호',nl:'Wachtwoord',vi:'Mật khẩu'},
  Page:{en:'Page',es:'Página','pt-BR':'Página',de:'Seite',fr:'Page',it:'Pagina',ja:'ページ',ar:'الصفحة',id:'Halaman',tr:'Sayfa',pl:'Strona',ko:'페이지',nl:'Pagina',vi:'Trang'},
  Pages:{en:'Pages',es:'Páginas','pt-BR':'Páginas',de:'Seiten',fr:'Pages',it:'Pagine',ja:'ページ',ar:'الصفحات',id:'Halaman',tr:'Sayfalar',pl:'Strony',ko:'페이지',nl:'Pagina’s',vi:'Trang'},
  Metadata:{en:'Metadata',es:'Metadatos','pt-BR':'Metadados',de:'Metadaten',fr:'Métadonnées',it:'Metadati',ja:'メタデータ',ar:'البيانات الوصفية',id:'Metadata',tr:'Meta Veri',pl:'Metadane',ko:'메타데이터',nl:'Metadata',vi:'Siêu dữ liệu'},
  Audio:{en:'Audio',es:'Audio','pt-BR':'Áudio',de:'Audio',fr:'Audio',it:'Audio',ja:'音声',ar:'الصوت',id:'Audio',tr:'Ses',pl:'Audio',ko:'오디오',nl:'Audio',vi:'Âm thanh'},
  Video:{en:'Video',es:'Vídeo','pt-BR':'Vídeo',de:'Video',fr:'Vidéo',it:'Video',ja:'動画',ar:'الفيديو',id:'Video',tr:'Video',pl:'Wideo',ko:'비디오',nl:'Video',vi:'Video'},
  Price:{en:'Price',es:'Precio','pt-BR':'Preço',de:'Preis',fr:'Prix',it:'Prezzo',ja:'価格',ar:'السعر',id:'Harga',tr:'Fiyat',pl:'Cena',ko:'가격',nl:'Prijs',vi:'Giá'},
  Cost:{en:'Cost',es:'Costo','pt-BR':'Custo',de:'Kosten',fr:'Coût',it:'Costo',ja:'コスト',ar:'التكلفة',id:'Biaya',tr:'Maliyet',pl:'Koszt',ko:'비용',nl:'Kosten',vi:'Chi phí'},
  Profit:{en:'Profit',es:'Beneficio','pt-BR':'Lucro',de:'Gewinn',fr:'Profit',it:'Profitto',ja:'利益',ar:'الربح',id:'Laba',tr:'Kâr',pl:'Zysk',ko:'이익',nl:'Winst',vi:'Lợi nhuận'},
  Interest:{en:'Interest',es:'Interés','pt-BR':'Juros',de:'Zins',fr:'Intérêt',it:'Interesse',ja:'利息',ar:'الفائدة',id:'Bunga',tr:'Faiz',pl:'Odsetki',ko:'이자',nl:'Rente',vi:'Lãi suất'},
  Loan:{en:'Loan',es:'Préstamo','pt-BR':'Empréstimo',de:'Kredit',fr:'Prêt',it:'Prestito',ja:'ローン',ar:'القرض',id:'Pinjaman',tr:'Kredi',pl:'Kredyt',ko:'대출',nl:'Lening',vi:'Khoản vay'},
  Concrete:{en:'Concrete',es:'Hormigón','pt-BR':'Concreto',de:'Beton',fr:'Béton',it:'Calcestruzzo',ja:'コンクリート',ar:'الخرسانة',id:'Beton',tr:'Beton',pl:'Beton',ko:'콘크리트',nl:'Beton',vi:'Bê tông'},
  Tile:{en:'Tile',es:'Baldosas','pt-BR':'Azulejos',de:'Fliesen',fr:'Carrelage',it:'Piastrelle',ja:'タイル',ar:'البلاط',id:'Ubin',tr:'Fayans',pl:'Płytki',ko:'타일',nl:'Tegels',vi:'Gạch lát'},
  Paint:{en:'Paint',es:'Pintura','pt-BR':'Tinta',de:'Farbe',fr:'Peinture',it:'Vernice',ja:'塗料',ar:'الطلاء',id:'Cat',tr:'Boya',pl:'Farba',ko:'페인트',nl:'Verf',vi:'Sơn'},
};

const connector: L = {en:'',es:'de','pt-BR':'de',de:'',fr:'de',it:'di',ja:'',ar:'',id:'',tr:'',pl:'',ko:'',nl:'',vi:''};
const prefixLocales=new Set<LocaleId>(['es','pt-BR','fr','it','ar','id','pl','vi']);
const noSpaceLocales=new Set<LocaleId>(['ja']);

function replaceWords(locale:LocaleId,input:string):string {
  if(locale==='en') return input;
  let out=input;
  const entries=Object.entries(words).sort((a,b)=>b[0].length-a[0].length);
  for(const [source,map] of entries) out=out.replace(new RegExp(`\\b${source}\\b`,'gi'),map[locale]);
  const tiny:Record<string,L>={
    Remove:{en:'Remove',es:'Eliminar','pt-BR':'Remover',de:'Entfernen',fr:'Supprimer',it:'Rimuovi',ja:'削除',ar:'إزالة',id:'Hapus',tr:'Kaldır',pl:'Usuń',ko:'제거',nl:'Verwijder',vi:'Xóa'},
    Add:{en:'Add',es:'Añadir','pt-BR':'Adicionar',de:'Hinzufügen',fr:'Ajouter',it:'Aggiungi',ja:'追加',ar:'إضافة',id:'Tambah',tr:'Ekle',pl:'Dodaj',ko:'추가',nl:'Toevoegen',vi:'Thêm'},
    Merge:{en:'Merge',es:'Unir','pt-BR':'Mesclar',de:'Zusammenführen',fr:'Fusionner',it:'Unisci',ja:'結合',ar:'دمج',id:'Gabungkan',tr:'Birleştir',pl:'Scal',ko:'병합',nl:'Samenvoegen',vi:'Gộp'},
    Split:{en:'Split',es:'Dividir','pt-BR':'Dividir',de:'Teilen',fr:'Diviser',it:'Dividi',ja:'分割',ar:'تقسيم',id:'Pisahkan',tr:'Böl',pl:'Podziel',ko:'분할',nl:'Splits',vi:'Tách'},
    Rotate:{en:'Rotate',es:'Rotar','pt-BR':'Girar',de:'Drehen',fr:'Pivoter',it:'Ruota',ja:'回転',ar:'تدوير',id:'Putar',tr:'Döndür',pl:'Obróć',ko:'회전',nl:'Draaien',vi:'Xoay'},
    Compress:{en:'Compress',es:'Comprimir','pt-BR':'Comprimir',de:'Komprimieren',fr:'Compresser',it:'Comprimi',ja:'圧縮',ar:'ضغط',id:'Kompres',tr:'Sıkıştır',pl:'Kompresuj',ko:'압축',nl:'Comprimeren',vi:'Nén'},
    Resize:{en:'Resize',es:'Redimensionar','pt-BR':'Redimensionar',de:'Größe ändern',fr:'Redimensionner',it:'Ridimensiona',ja:'リサイズ',ar:'تغيير الحجم',id:'Ubah ukuran',tr:'Boyutlandır',pl:'Zmień rozmiar',ko:'크기 변경',nl:'Formaat wijzigen',vi:'Đổi kích thước'},
    Crop:{en:'Crop',es:'Recortar','pt-BR':'Recortar',de:'Zuschneiden',fr:'Recadrer',it:'Ritaglia',ja:'切り抜き',ar:'قص',id:'Potong',tr:'Kırp',pl:'Przytnij',ko:'자르기',nl:'Bijsnijden',vi:'Cắt'},
  };
  for(const [source,map] of Object.entries(tiny)) out=out.replace(new RegExp(`\\b${source}\\b`,'gi'),map[locale]);
  return out;
}

export function categoryName(locale:LocaleId, english:string):string { return categories[english]?.[locale] ?? english; }

export function toolName(locale:LocaleId, tool:Pick<ToolDefinition,'name'>|string):string {
  const name=typeof tool==='string'?tool:tool.name;if(locale==='en')return name;
  const conversion=name.match(/^(.+?)\s+to\s+(.+?)(?:\s+Converter)?$/i);
  if(conversion){const a=replaceWords(locale,conversion[1]!),b=replaceWords(locale,conversion[2]!);const forms:L={en:`${a} to ${b} Converter`,es:`Convertidor de ${a} a ${b}`,'pt-BR':`Conversor de ${a} para ${b}`,de:`${a}-zu-${b}-Konverter`,fr:`Convertisseur ${a} vers ${b}`,it:`Convertitore da ${a} a ${b}`,ja:`${a}→${b} コンバーター`,ar:`محول ${a} إلى ${b}`,id:`Konverter ${a} ke ${b}`,tr:`${a} - ${b} Dönüştürücü`,pl:`Konwerter ${a} na ${b}`,ko:`${a} → ${b} 변환기`,nl:`${a} naar ${b} converter`,vi:`Bộ chuyển đổi ${a} sang ${b}`};return forms[locale];}
  for(const [type,map] of Object.entries(types)) if(name.endsWith(` ${type}`)){const subject=replaceWords(locale,name.slice(0,-type.length-1)),kind=map[locale];if(noSpaceLocales.has(locale))return `${subject}${kind}`;if(prefixLocales.has(locale)){const c=connector[locale];return `${kind}${c?` ${c}`:''} ${subject}`;}return `${subject} ${kind}`;}
  return replaceWords(locale,name);
}

const seoSuffix:L={en:'Free Online Tool',es:'Herramienta online gratis','pt-BR':'Ferramenta online grátis',de:'Kostenloses Online-Tool',fr:'Outil en ligne gratuit',it:'Strumento online gratuito',ja:'無料オンラインツール',ar:'أداة مجانية عبر الإنترنت',id:'Alat online gratis',tr:'Ücretsiz çevrimiçi araç',pl:'Darmowe narzędzie online',ko:'무료 온라인 도구',nl:'Gratis online tool',vi:'Công cụ trực tuyến miễn phí'};
const descTemplate:L={en:'Use {name} free in your browser. Fast, simple and privacy-first; supported files are processed locally.',es:'Usa {name} gratis en tu navegador. Rápido, sencillo y centrado en la privacidad; los archivos compatibles se procesan localmente.','pt-BR':'Use {name} grátis no navegador. Rápido, simples e focado em privacidade; arquivos compatíveis são processados localmente.',de:'Nutze {name} kostenlos im Browser. Schnell, einfach und datenschutzfreundlich; unterstützte Dateien werden lokal verarbeitet.',fr:'Utilisez {name} gratuitement dans votre navigateur. Rapide, simple et respectueux de la vie privée; les fichiers pris en charge sont traités localement.',it:'Usa {name} gratis nel browser. Veloce, semplice e orientato alla privacy; i file supportati vengono elaborati in locale.',ja:'{name}をブラウザで無料利用。高速・シンプル・プライバシー重視で、対応ファイルは端末内で処理されます。',ar:'استخدم {name} مجانًا في متصفحك. سريع وبسيط ويركز على الخصوصية؛ تتم معالجة الملفات المدعومة محليًا.',id:'Gunakan {name} gratis di browser. Cepat, sederhana, dan mengutamakan privasi; file yang didukung diproses secara lokal.',tr:'{name} aracını tarayıcınızda ücretsiz kullanın. Hızlı, basit ve gizlilik odaklıdır; desteklenen dosyalar yerel olarak işlenir.',pl:'Korzystaj z {name} bezpłatnie w przeglądarce. Szybko, prosto i z myślą o prywatności; obsługiwane pliki są przetwarzane lokalnie.',ko:'{name}을(를) 브라우저에서 무료로 사용하세요. 빠르고 간단하며 개인정보 보호를 우선하고, 지원 파일은 로컬에서 처리됩니다.',nl:'Gebruik {name} gratis in je browser. Snel, eenvoudig en privacygericht; ondersteunde bestanden worden lokaal verwerkt.',vi:'Dùng {name} miễn phí ngay trong trình duyệt. Nhanh, đơn giản, ưu tiên quyền riêng tư; tệp được hỗ trợ được xử lý cục bộ.'};
const howTitle:L={en:'How it works',es:'Cómo funciona','pt-BR':'Como funciona',de:'So funktioniert es',fr:'Comment ça marche',it:'Come funziona',ja:'使い方',ar:'كيف يعمل',id:'Cara kerja',tr:'Nasıl çalışır',pl:'Jak to działa',ko:'사용 방법',nl:'Hoe het werkt',vi:'Cách hoạt động'};
const howBody:L={en:'Enter or upload the requested input, run the tool and review the result immediately. No account is required, and file tools process data in your browser whenever supported.',es:'Introduce o sube los datos solicitados, ejecuta la herramienta y revisa el resultado al instante. No necesitas una cuenta y las herramientas de archivos procesan los datos en tu navegador.', 'pt-BR':'Insira ou envie os dados solicitados, execute a ferramenta e veja o resultado imediatamente. Não é preciso criar conta e as ferramentas de arquivo processam os dados no navegador.',de:'Gib die gewünschten Daten ein oder lade eine Datei hoch, starte das Tool und sieh das Ergebnis sofort. Kein Konto nötig; Dateiwerkzeuge verarbeiten Daten im Browser.',fr:'Saisissez ou importez les données demandées, lancez l’outil et consultez immédiatement le résultat. Aucun compte requis; les outils de fichiers traitent les données dans le navigateur.',it:'Inserisci o carica i dati richiesti, avvia lo strumento e visualizza subito il risultato. Non serve un account e gli strumenti per file elaborano i dati nel browser.',ja:'必要な値を入力またはファイルをアップロードし、ツールを実行すると結果をすぐ確認できます。アカウントは不要で、対応するファイル処理はブラウザ内で行われます。',ar:'أدخل البيانات المطلوبة أو ارفع الملف ثم شغّل الأداة واعرض النتيجة فورًا. لا يلزم حساب، وتتم معالجة الملفات المدعومة داخل المتصفح.',id:'Masukkan atau unggah data yang diminta, jalankan alat, lalu lihat hasilnya seketika. Tidak perlu akun dan alat file memproses data di browser.',tr:'İstenen veriyi girin veya dosyayı yükleyin, aracı çalıştırın ve sonucu hemen görüntüleyin. Hesap gerekmez; dosya araçları veriyi tarayıcıda işler.',pl:'Wprowadź lub prześlij wymagane dane, uruchom narzędzie i od razu sprawdź wynik. Konto nie jest potrzebne, a narzędzia plikowe przetwarzają dane w przeglądarce.',ko:'필요한 값을 입력하거나 파일을 업로드한 뒤 도구를 실행하면 결과를 즉시 확인할 수 있습니다. 계정은 필요 없으며 지원되는 파일 처리는 브라우저에서 수행됩니다.',nl:'Voer de gevraagde gegevens in of upload een bestand, start de tool en bekijk direct het resultaat. Geen account nodig; bestandstools verwerken gegevens in je browser.',vi:'Nhập hoặc tải lên dữ liệu cần thiết, chạy công cụ và xem kết quả ngay. Không cần tài khoản; các công cụ tệp xử lý dữ liệu trong trình duyệt.'};

export function toolSeoCopy(locale:LocaleId,tool:ToolDefinition){const name=toolName(locale,tool);return{displayName:name,title:`${name} — ${seoSuffix[locale]}`,description:descTemplate[locale].replace('{name}',name)};}
export function howItWorks(locale:LocaleId){return{title:howTitle[locale],body:howBody[locale]};}
export function localizeLabel(locale:LocaleId,label:string):string{return replaceWords(locale,label);}
export function categoryDescription(locale:LocaleId,name:string,count:number){const n=categoryName(locale,name);const templates:L={en:`${count} free ${n.toLowerCase()} that run in your browser.`,es:`${count} herramientas gratuitas de ${n.toLowerCase()} que funcionan en tu navegador.`,'pt-BR':`${count} ferramentas grátis de ${n.toLowerCase()} que funcionam no navegador.`,de:`${count} kostenlose ${n}, die direkt im Browser laufen.`,fr:`${count} outils gratuits — ${n.toLowerCase()} — dans votre navigateur.`,it:`${count} strumenti gratuiti di ${n.toLowerCase()} che funzionano nel browser.`,ja:`ブラウザで使える無料の${n}を${count}個収録。`,ar:`${count} أداة مجانية ضمن ${n} تعمل في متصفحك.`,id:`${count} ${n} gratis yang berjalan di browser.`,tr:`Tarayıcıda çalışan ${count} ücretsiz ${n}.`,pl:`${count} darmowych narzędzi: ${n}, działających w przeglądarce.`,ko:`브라우저에서 실행되는 무료 ${n} ${count}개.`,nl:`${count} gratis ${n} die in je browser werken.`,vi:`${count} ${n} miễn phí chạy trong trình duyệt.`};return templates[locale];}
const homeIntroText:L={en:'{count} free tools ready to use, organized into focused categories. File processing stays in your browser whenever the tool supports local execution.',es:'{count} herramientas gratuitas listas para usar, organizadas por categorías. El procesamiento de archivos permanece en tu navegador cuando la herramienta admite ejecución local.','pt-BR':'{count} ferramentas grátis prontas para usar, organizadas por categorias. O processamento de arquivos fica no navegador sempre que a ferramenta oferece execução local.',de:'{count} kostenlose Tools, übersichtlich nach Kategorien organisiert. Dateiverarbeitung bleibt im Browser, wenn das Tool lokale Verarbeitung unterstützt.',fr:'{count} outils gratuits prêts à l’emploi, organisés par catégories. Le traitement des fichiers reste dans votre navigateur lorsque l’outil fonctionne localement.',it:'{count} strumenti gratuiti pronti all’uso, organizzati per categorie. L’elaborazione dei file resta nel browser quando lo strumento supporta l’esecuzione locale.',ja:'すぐ使える無料ツールを{count}個、カテゴリ別に収録。対応するファイル処理はブラウザ内で完結します。',ar:'{count} أداة مجانية جاهزة للاستخدام ومنظمة حسب الفئات. تبقى معالجة الملفات داخل متصفحك عندما تدعم الأداة التنفيذ المحلي.',id:'{count} alat gratis siap digunakan dan tersusun dalam kategori. Pemrosesan file tetap di browser saat alat mendukung eksekusi lokal.',tr:'Kategorilere ayrılmış, kullanıma hazır {count} ücretsiz araç. Yerel çalışmayı destekleyen dosya araçlarında veriler tarayıcınızda kalır.',pl:'{count} darmowych narzędzi gotowych do użycia, uporządkowanych według kategorii. Obsługiwane pliki są przetwarzane lokalnie w przeglądarce.',ko:'카테고리별로 정리된 무료 도구 {count}개를 바로 사용할 수 있습니다. 지원되는 파일 처리는 브라우저에서 로컬로 수행됩니다.',nl:'{count} gratis tools klaar voor gebruik, geordend per categorie. Bestandsverwerking blijft in je browser wanneer lokale uitvoering wordt ondersteund.',vi:'{count} công cụ miễn phí sẵn sàng sử dụng, được sắp xếp theo danh mục. Việc xử lý tệp diễn ra trong trình duyệt khi công cụ hỗ trợ xử lý cục bộ.'};
const entriesText:L={en:'{count} tools',es:'{count} herramientas','pt-BR':'{count} ferramentas',de:'{count} Tools',fr:'{count} outils',it:'{count} strumenti',ja:'{count}ツール',ar:'{count} أداة',id:'{count} alat',tr:'{count} araç',pl:'{count} narzędzi',ko:'도구 {count}개',nl:'{count} tools',vi:'{count} công cụ'};
export function homeIntro(locale:LocaleId,count:number){return homeIntroText[locale].replace('{count}',String(count));}
export function toolsCount(locale:LocaleId,count:number){return entriesText[locale].replace('{count}',String(count));}
