import type { LocaleId } from "../core/types.ts";
import type { ToolEditorial } from "./tool-editorial.ts";
import {
  bi,
  calculatorEditorial,
  type CalculatorEditorialDefinition
} from "./editorial-factories.ts";

const defs: CalculatorEditorialDefinition[] = [

  {
    id: "margin-calculator",
    title: bi("Calculate gross margin from revenue and cost", "Calcola il margine lordo da ricavi e costi"),
    intro: bi("Measure the share of revenue left after subtracting cost.", "Misura la quota dei ricavi che rimane dopo aver sottratto il costo."),
    formula: "(revenue − cost) ÷ revenue × 100",
    example: bi("Revenue 1000, cost 600 → margin 40%", "Ricavi 1000, costo 600 → margine 40%"),
    insightTitle: bi("Margin uses revenue as its reference", "Il margine usa i ricavi come riferimento"),
    insightBody: bi("This is why margin and markup can produce different percentages from the same price and cost.", "Per questo margine e markup possono produrre percentuali diverse partendo dagli stessi prezzo e costo.")
  },

  {
    id: "markup-calculator",
    title: bi("Calculate markup over cost", "Calcola il markup sul costo"),
    intro: bi("Measure how much the selling price exceeds cost relative to that cost.", "Misura quanto il prezzo di vendita supera il costo rispetto al costo stesso."),
    formula: "(price − cost) ÷ cost × 100",
    example: bi("Price 100, cost 60 → markup 66.67%", "Prezzo 100, costo 60 → markup 66,67%"),
    insightTitle: bi("Markup and margin use different denominators", "Markup e margine usano denominatori diversi"),
    insightBody: bi("Markup divides profit by cost; margin divides profit by revenue.", "Il markup divide il profitto per il costo; il margine divide il profitto per i ricavi.")
  },

  {
    id: "profit-calculator",
    title: bi("Calculate profit from revenue and cost", "Calcola il profitto da ricavi e costi"),
    intro: bi("Subtract total cost from revenue to calculate the remaining profit.", "Sottrae il costo totale dai ricavi per ottenere il profitto."),
    formula: "profit = revenue − cost",
    example: bi("1000 − 700 = 300 profit", "1000 − 700 = 300 di profitto"),
    insightTitle: bi("Profit is an amount, margin is a percentage", "Il profitto è un importo, il margine è una percentuale"),
    insightBody: bi("Two businesses can have the same profit but very different margins.", "Due attività possono avere lo stesso profitto ma margini percentuali molto diversi.")
  },

  {
    id: "break-even-calculator",
    title: bi("Estimate how many units cover fixed costs", "Stima quante unità servono per coprire i costi fissi"),
    intro: bi("Divide fixed costs by the contribution generated by each unit.", "Divide i costi fissi per il margine di contribuzione generato da ogni unità."),
    formula: "fixed costs ÷ (price − variable cost)",
    example: bi("10000 ÷ (50 − 30) = 500 units", "10000 ÷ (50 − 30) = 500 unità"),
    insightTitle: bi("Only contribution per unit covers fixed costs", "Solo il margine di contribuzione copre i costi fissi"),
    insightBody: bi("Revenue per unit is not enough by itself because variable cost must be paid first.", "Il ricavo per unità non basta perché prima devono essere sostenuti i costi variabili.")
  },

  {
    id: "roi-calculator",
    title: bi("Calculate return on investment", "Calcola il ritorno sull’investimento"),
    intro: bi("Compare the gain above the original investment with the investment cost.", "Confronta il guadagno oltre l’investimento iniziale con il costo dell’investimento."),
    formula: "(gain − cost) ÷ cost × 100",
    example: bi("1300 from 1000 invested → ROI 30%", "1300 da 1000 investiti → ROI 30%"),
    insightTitle: bi("ROI expresses return relative to invested capital", "Il ROI esprime il rendimento rispetto al capitale investito"),
    insightBody: bi("An absolute gain alone does not show how large the return was relative to the original investment.", "Il solo guadagno assoluto non mostra quanto sia stato grande il rendimento rispetto all’investimento iniziale.")
  },

  {
    id: "roas-calculator",
    title: bi("Calculate return on advertising spend", "Calcola il ritorno sulla spesa pubblicitaria"),
    intro: bi("Compare attributed revenue with the amount spent on advertising.", "Confronta i ricavi attribuiti con la spesa pubblicitaria."),
    formula: "attributed revenue ÷ ad spend",
    example: bi("5000 revenue ÷ 1000 spend = 5× ROAS", "5000 di ricavi ÷ 1000 di spesa = ROAS 5×"),
    insightTitle: bi("ROAS measures revenue, not profit", "Il ROAS misura i ricavi, non il profitto"),
    insightBody: bi("A high ROAS does not automatically mean a campaign is profitable after product and operating costs.", "Un ROAS elevato non significa automaticamente che una campagna sia profittevole dopo costi di prodotto e operativi.")
  },

  {
    id: "cac-calculator",
    title: bi("Calculate customer acquisition cost", "Calcola il costo di acquisizione cliente"),
    intro: bi("Spread marketing and sales acquisition costs across newly acquired customers.", "Distribuisce i costi di marketing e vendita sui nuovi clienti acquisiti."),
    formula: "(marketing + sales costs) ÷ new customers",
    example: bi("5000 + 3000 across 100 customers → CAC 80", "5000 + 3000 su 100 clienti → CAC 80"),
    insightTitle: bi("CAC becomes more useful when compared with LTV", "Il CAC è più utile se confrontato con l’LTV"),
    insightBody: bi("Acquisition cost alone does not show whether customers generate enough value over their lifetime.", "Il solo costo di acquisizione non mostra se i clienti generano abbastanza valore nel tempo.")
  },

  {
    id: "ltv-calculator",
    title: bi("Estimate customer lifetime value", "Stima il valore del cliente nel tempo"),
    intro: bi("Estimate customer value from purchase amount, purchase frequency, gross margin and lifespan.", "Stima il valore del cliente usando acquisto medio, frequenza, margine lordo e durata della relazione."),
    formula: "purchase × frequency × margin × years",
    example: bi("50 × 6 × 60% × 3 = 540 estimated LTV", "50 × 6 × 60% × 3 = LTV stimato 540"),
    insightTitle: bi("LTV is an estimate based on assumptions", "L’LTV è una stima basata su ipotesi"),
    insightBody: bi("Changes in retention, margin or buying frequency can substantially change the result.", "Variazioni di retention, margine o frequenza d’acquisto possono cambiare molto il risultato.")
  },

  {
    id: "conversion-rate-calculator",
    title: bi("Calculate conversion rate", "Calcola il tasso di conversione"),
    intro: bi("Measure what percentage of visitors completed the desired conversion.", "Misura quale percentuale dei visitatori ha completato la conversione desiderata."),
    formula: "conversions ÷ visitors × 100",
    example: bi("50 conversions from 1000 visitors = 5%", "50 conversioni su 1000 visitatori = 5%"),
    insightTitle: bi("The denominator defines the meaning of the rate", "Il denominatore definisce il significato del tasso"),
    insightBody: bi("Visitors, sessions and clicks are different populations and can produce different conversion rates.", "Visitatori, sessioni e click sono popolazioni diverse e possono produrre tassi di conversione differenti.")
  },

  {
    id: "churn-rate-calculator",
    title: bi("Calculate customer churn rate", "Calcola il tasso di abbandono dei clienti"),
    intro: bi("Measure the share of starting customers lost during a period.", "Misura la quota di clienti iniziali persi durante un periodo."),
    formula: "customers lost ÷ customers at start × 100",
    example: bi("50 lost from 1000 starting customers = 5%", "50 persi su 1000 clienti iniziali = 5%"),
    insightTitle: bi("Churn depends on the measurement period", "Il churn dipende dal periodo considerato"),
    insightBody: bi("Monthly and annual churn rates should not be compared as if they represented the same time interval.", "Tassi di churn mensili e annuali non devono essere confrontati come se rappresentassero lo stesso intervallo.")
  },

  {
    id: "growth-rate-calculator",
    title: bi("Calculate percentage growth", "Calcola la crescita percentuale"),
    intro: bi("Compare an ending value with its starting value.", "Confronta un valore finale con il valore iniziale."),
    formula: "(end − start) ÷ |start| × 100",
    example: bi("100 → 125 = 25% growth", "100 → 125 = crescita del 25%"),
    insightTitle: bi("Growth rate uses the starting value as the baseline", "Il tasso di crescita usa il valore iniziale come riferimento"),
    insightBody: bi("The same absolute increase produces a different percentage depending on where the series started.", "Lo stesso aumento assoluto produce percentuali diverse a seconda del valore di partenza.")
  },

  {
    id: "cagr-calculator",
    title: bi("Calculate compound annual growth rate", "Calcola il tasso annuo composto di crescita"),
    intro: bi("Find the constant annual rate that would connect a starting value to an ending value over several years.", "Trova il tasso annuo costante che collegherebbe un valore iniziale a uno finale in più anni."),
    formula: "(end ÷ start)^(1 ÷ years) − 1",
    example: bi("1000 → 1500 in 5 years ≈ 8.45% CAGR", "1000 → 1500 in 5 anni ≈ CAGR 8,45%"),
    insightTitle: bi("CAGR smooths the path between start and end", "Il CAGR uniforma il percorso tra inizio e fine"),
    insightBody: bi("It does not show year-by-year volatility; it represents an equivalent constant annual rate.", "Non mostra la volatilità anno per anno, ma rappresenta un tasso annuo costante equivalente.")
  },

  {
    id: "simple-interest-calculator",
    title: bi("Calculate simple interest", "Calcola l’interesse semplice"),
    intro: bi("Interest is calculated only on the original principal for the full duration.", "L’interesse viene calcolato soltanto sul capitale iniziale per tutta la durata."),
    formula: "principal × rate × years",
    example: bi("10000 at 5% for 3 years → 1500 interest", "10000 al 5% per 3 anni → 1500 di interessi"),
    insightTitle: bi("Simple interest does not compound", "L’interesse semplice non capitalizza"),
    insightBody: bi("Previously earned interest does not itself generate additional interest.", "Gli interessi già maturati non generano a loro volta nuovi interessi.")
  },

  {
    id: "compound-interest-calculator",
    title: bi("Calculate compound interest", "Calcola l’interesse composto"),
    intro: bi("Interest is periodically added to the balance so later interest also applies to earlier interest.", "Gli interessi vengono periodicamente aggiunti al capitale, quindi gli interessi successivi maturano anche su quelli precedenti."),
    formula: "P × (1 + r/m)^(m×t)",
    example: bi("Compounding frequency affects the final amount.", "La frequenza di capitalizzazione influenza l’importo finale."),
    insightTitle: bi("Compounding creates growth on previous growth", "La capitalizzazione genera crescita sulla crescita precedente"),
    insightBody: bi("That is the key mathematical difference from simple interest.", "Questa è la principale differenza matematica rispetto all’interesse semplice.")
  },

  {
    id: "loan-payment-calculator",
    title: bi("Estimate a fixed monthly loan payment", "Stima la rata mensile di un prestito"),
    intro: bi("Calculate the fixed payment for an amortizing loan using principal, annual rate and term.", "Calcola la rata costante di un prestito ammortizzato usando capitale, tasso annuo e durata."),
    formula: "P × r × (1+r)^n ÷ ((1+r)^n − 1)",
    example: bi("The rate is converted to a monthly rate and the term to months.", "Il tasso viene convertito in tasso mensile e la durata in mesi."),
    insightTitle: bi("A longer term lowers payments but can increase total interest", "Una durata maggiore riduce la rata ma può aumentare gli interessi totali"),
    insightBody: bi("Lower monthly payments spread repayment over more interest-bearing periods.", "Rate più basse distribuiscono il rimborso su un maggior numero di periodi soggetti a interessi.")
  },

  {
    id: "amortization-calculator",
    title: bi("Estimate payment and total loan interest", "Stima rata e interessi totali di un prestito"),
    intro: bi("Calculate monthly payment, total amount repaid and total interest for an amortizing loan.", "Calcola rata mensile, importo totale rimborsato e interessi totali per un prestito ammortizzato."),
    formula: "fixed payment over n monthly periods",
    example: bi("Total interest = total paid − principal", "Interessi totali = totale pagato − capitale"),
    insightTitle: bi("Early payments contain more interest", "Le prime rate contengono una quota maggiore di interessi"),
    insightBody: bi("In ordinary amortization, the interest component decreases as the outstanding balance falls.", "In un normale ammortamento, la quota interessi diminuisce man mano che il capitale residuo si riduce.")
  },

  {
    id: "savings-goal-calculator",
    title: bi("Estimate the monthly saving needed for a goal", "Stima il risparmio mensile necessario per un obiettivo"),
    intro: bi("Combine current savings, target amount, expected return and time horizon to estimate a monthly contribution.", "Combina risparmi attuali, obiettivo, rendimento previsto e orizzonte temporale per stimare il versamento mensile."),
    formula: "future-value annuity calculation",
    example: bi("Higher return or more time generally lowers the required monthly contribution.", "Un rendimento maggiore o più tempo riducono generalmente il versamento mensile necessario."),
    insightTitle: bi("Expected return is an assumption, not a guarantee", "Il rendimento atteso è un’ipotesi, non una garanzia"),
    insightBody: bi("Real investment returns can vary, so the result should be treated as an estimate.", "I rendimenti reali possono variare, quindi il risultato va considerato una stima.")
  },

  {
    id: "discount-calculator",
    title: bi("Calculate a discount and final price", "Calcola sconto e prezzo finale"),
    intro: bi("Find the amount removed from the original price and the price remaining after the discount.", "Trova l’importo sottratto dal prezzo originale e il prezzo finale dopo lo sconto."),
    formula: "discount = price × rate; final = price − discount",
    example: bi("100 with 20% off → discount 20, final 80", "100 con sconto 20% → sconto 20, prezzo finale 80"),
    insightTitle: bi("Successive discounts do not simply add", "Gli sconti successivi non si sommano semplicemente"),
    insightBody: bi("A second percentage discount is applied to the already reduced price.", "Un secondo sconto percentuale viene applicato al prezzo già ridotto.")
  },

  {
    id: "sale-price-calculator",
    title: bi("Calculate the price after a percentage discount", "Calcola il prezzo dopo uno sconto percentuale"),
    intro: bi("Multiply the original price by the share that remains after the discount.", "Moltiplica il prezzo originale per la quota che rimane dopo lo sconto."),
    formula: "price × (1 − discount ÷ 100)",
    example: bi("80 with 15% off → 68", "80 con sconto 15% → 68"),
    insightTitle: bi("A 15% discount means paying 85%", "Uno sconto del 15% significa pagare l’85%"),
    insightBody: bi("Working with the remaining percentage is often the fastest way to calculate a sale price.", "Usare la percentuale rimanente è spesso il modo più rapido per calcolare un prezzo scontato.")
  },

  {
    id: "price-per-unit-calculator",
    title: bi("Compare products by price per unit", "Confronta prodotti tramite il prezzo unitario"),
    intro: bi("Divide the total price by the quantity to normalize different package sizes.", "Divide il prezzo totale per la quantità per confrontare confezioni di dimensioni diverse."),
    formula: "total price ÷ quantity",
    example: bi("12.99 ÷ 6 ≈ 2.17 per unit", "12,99 ÷ 6 ≈ 2,17 per unità"),
    insightTitle: bi("Unit price makes different package sizes comparable", "Il prezzo unitario rende confrontabili confezioni diverse"),
    insightBody: bi("A cheaper package is not necessarily cheaper per unit.", "Una confezione dal prezzo totale più basso non è necessariamente più economica per unità.")
  },

  {
    id: "cpm-calculator",
    title: bi("Calculate cost per thousand impressions", "Calcola il costo per mille impression"),
    intro: bi("Normalize campaign cost to every one thousand ad impressions.", "Normalizza il costo della campagna ogni mille impression pubblicitarie."),
    formula: "cost ÷ impressions × 1000",
    example: bi("500 over 100000 impressions → CPM 5", "500 su 100000 impression → CPM 5"),
    insightTitle: bi("CPM measures exposure cost, not engagement", "Il CPM misura il costo dell’esposizione, non dell’interazione"),
    insightBody: bi("Impressions can occur without clicks or conversions.", "Le impression possono verificarsi senza click o conversioni.")
  },

  {
    id: "cpc-calculator",
    title: bi("Calculate cost per click", "Calcola il costo per click"),
    intro: bi("Divide campaign cost by the number of clicks generated.", "Divide il costo della campagna per il numero di click generati."),
    formula: "campaign cost ÷ clicks",
    example: bi("500 cost ÷ 1000 clicks = CPC 0.50", "500 di costo ÷ 1000 click = CPC 0,50"),
    insightTitle: bi("Low CPC does not automatically mean high performance", "Un CPC basso non significa automaticamente alte performance"),
    insightBody: bi("Cheap clicks still need to produce useful actions or revenue.", "Click economici devono comunque generare azioni utili o ricavi.")
  },

  {
    id: "ctr-calculator",
    title: bi("Calculate click-through rate", "Calcola il click-through rate"),
    intro: bi("Measure what percentage of impressions generated a click.", "Misura quale percentuale delle impression ha generato un click."),
    formula: "clicks ÷ impressions × 100",
    example: bi("1000 clicks from 100000 impressions = 1% CTR", "1000 click su 100000 impression = CTR 1%"),
    insightTitle: bi("CTR measures clicks relative to exposure", "Il CTR misura i click rispetto all’esposizione"),
    insightBody: bi("It does not directly measure sales, leads or profitability.", "Non misura direttamente vendite, lead o redditività.")
  },

  {
    id: "revenue-calculator",
    title: bi("Calculate revenue from price and quantity", "Calcola i ricavi da prezzo e quantità"),
    intro: bi("Multiply the selling price of each unit by the number of units sold.", "Moltiplica il prezzo di vendita unitario per il numero di unità vendute."),
    formula: "price per unit × quantity",
    example: bi("25 × 100 = 2500 revenue", "25 × 100 = 2500 di ricavi"),
    insightTitle: bi("Revenue is not the same as profit", "Ricavi e profitto non sono la stessa cosa"),
    insightBody: bi("Costs still need to be subtracted before determining profit.", "Prima di determinare il profitto devono ancora essere sottratti i costi.")
  },

  {
    id: "profit-margin-calculator",
    title: bi("Calculate profit and profit margin together", "Calcola insieme profitto e margine"),
    intro: bi("Subtract costs from revenue and express the resulting profit as a percentage of revenue.", "Sottrae i costi dai ricavi ed esprime il profitto risultante come percentuale dei ricavi."),
    formula: "profit = revenue − cost; margin = profit ÷ revenue × 100",
    example: bi("1000 revenue, 700 cost → profit 300, margin 30%", "1000 ricavi, 700 costi → profitto 300, margine 30%"),
    insightTitle: bi("Profit and margin answer different questions", "Profitto e margine rispondono a domande diverse"),
    insightBody: bi("Profit measures the amount earned; margin measures how much of each revenue unit remains as profit.", "Il profitto misura l’importo guadagnato; il margine misura quale quota dei ricavi rimane come profitto.")
  },

  {
    id: "inventory-turnover-calculator",
    title: bi("Calculate inventory turnover", "Calcola la rotazione del magazzino"),
    intro: bi("Compare cost of goods sold with average inventory.", "Confronta il costo del venduto con il valore medio del magazzino."),
    formula: "COGS ÷ average inventory",
    example: bi("500000 ÷ 100000 = 5× turnover", "500000 ÷ 100000 = rotazione 5×"),
    insightTitle: bi("Turnover is a frequency ratio", "La rotazione è un rapporto di frequenza"),
    insightBody: bi("A value of 5 means inventory equivalent to the average stock was cycled roughly five times over the measured period.", "Un valore di 5 indica che un volume equivalente al magazzino medio è stato ruotato circa cinque volte nel periodo considerato.")
  },

  {
    id: "burn-rate-calculator",
    title: bi("Calculate average monthly cash burn", "Calcola il consumo medio mensile di cassa"),
    intro: bi("Measure how much cash was consumed per month over a selected period.", "Misura quanta cassa è stata consumata mediamente ogni mese nel periodo selezionato."),
    formula: "(starting cash − ending cash) ÷ months",
    example: bi("500000 → 350000 over 3 months = 50000/month", "500000 → 350000 in 3 mesi = 50000/mese"),
    insightTitle: bi("Burn rate is an average", "Il burn rate è una media"),
    insightBody: bi("Actual monthly spending can vary even when the calculated average remains constant.", "La spesa reale può variare di mese in mese anche se la media calcolata resta costante.")
  },

  {
    id: "runway-calculator",
    title: bi("Estimate how many months cash will last", "Stima per quanti mesi durerà la cassa"),
    intro: bi("Divide available cash by average monthly burn.", "Divide la liquidità disponibile per il consumo medio mensile."),
    formula: "cash available ÷ monthly burn",
    example: bi("250000 ÷ 50000 = 5 months runway", "250000 ÷ 50000 = 5 mesi di runway"),
    insightTitle: bi("Runway assumes burn remains similar", "Il runway presume un burn rate simile nel tempo"),
    insightBody: bi("If spending or revenue changes significantly, actual runway will also change.", "Se spese o ricavi cambiano significativamente, cambierà anche il runway reale.")
  },

  {
    id: "commission-calculator",
    title: bi("Calculate commission from sales", "Calcola la commissione sulle vendite"),
    intro: bi("Apply a commission percentage to the sales amount.", "Applica una percentuale di commissione all’importo delle vendite."),
    formula: "sales × commission rate ÷ 100",
    example: bi("10000 at 5% = 500 commission", "10000 al 5% = 500 di commissione"),
    insightTitle: bi("Commission rate and total compensation are different", "Tasso di commissione e compenso totale sono diversi"),
    insightBody: bi("Base salary, tiers and bonuses are not included unless they are separately added to the calculation.", "Stipendio base, scaglioni e bonus non sono inclusi se non vengono considerati separatamente.")
  },

  {
    id: "unit-economics-calculator",
    title: bi("Understand revenue and contribution per unit", "Analizza ricavi e contribuzione per unità"),
    intro: bi("Normalize total revenue and variable costs by units or customers.", "Normalizza ricavi totali e costi variabili per unità o cliente."),
    formula: "revenue/unit − variable cost/unit",
    example: bi("100000 revenue and 60000 variable cost over 1000 units → contribution 40/unit", "100000 ricavi e 60000 costi variabili su 1000 unità → contribuzione 40/unità"),
    insightTitle: bi("Positive contribution is not the same as overall profit", "Contribuzione positiva non significa profitto complessivo"),
    insightBody: bi("Fixed costs still need to be covered after calculating contribution per unit.", "Dopo aver calcolato la contribuzione per unità devono ancora essere coperti i costi fissi.")
  }

];

export const calculatorBusinessEditorialBatch:
  Partial<Record<string, Partial<Record<LocaleId, ToolEditorial>>>> =
  Object.fromEntries(
    defs.map((def) => [def.id, calculatorEditorial(def)])
  );
