import type { LocaleId } from '../core/types.ts';

type UiCopy = {
  siteName: string;
  tagline: string;
  search: string;
  searchPlaceholder: string;
  categories: string;
  allTools: string;
  calculate: string;
  reset: string;
  result: string;
  copy: string;
  copied: string;
  related: string;
  privacyLocal: string;
  localDetail: string;
  ad: string;
  language: string;
  unavailable: string;
  unavailableDetail: string;
  home: string;
  tools: string;
};

const copy: Record<LocaleId, UiCopy> = {
  en: { siteName:'Utility Platform', tagline:'Fast, private tools that work in your browser.', search:'Search', searchPlaceholder:'Search tools…', categories:'Categories', allTools:'All tools', calculate:'Calculate', reset:'Reset', result:'Result', copy:'Copy', copied:'Copied', related:'Related tools', privacyLocal:'Runs locally', localDetail:'Your inputs stay in your browser.', ad:'Advertisement', language:'Language', unavailable:'Tool engine in progress', unavailableDetail:'This route is wired into the final catalog, but its execution engine has not been enabled in this development build yet.', home:'Home', tools:'Tools' },
  es: { siteName:'Utility Platform', tagline:'Herramientas rápidas y privadas que funcionan en tu navegador.', search:'Buscar', searchPlaceholder:'Buscar herramientas…', categories:'Categorías', allTools:'Todas las herramientas', calculate:'Calcular', reset:'Restablecer', result:'Resultado', copy:'Copiar', copied:'Copiado', related:'Herramientas relacionadas', privacyLocal:'Funciona localmente', localDetail:'Tus datos permanecen en tu navegador.', ad:'Publicidad', language:'Idioma', unavailable:'Motor en desarrollo', unavailableDetail:'La ruta ya forma parte del catálogo final, pero su motor todavía no está activo en esta compilación de desarrollo.', home:'Inicio', tools:'Herramientas' },
  'pt-BR': { siteName:'Utility Platform', tagline:'Ferramentas rápidas e privadas que funcionam no seu navegador.', search:'Pesquisar', searchPlaceholder:'Pesquisar ferramentas…', categories:'Categorias', allTools:'Todas as ferramentas', calculate:'Calcular', reset:'Redefinir', result:'Resultado', copy:'Copiar', copied:'Copiado', related:'Ferramentas relacionadas', privacyLocal:'Processamento local', localDetail:'Seus dados permanecem no navegador.', ad:'Publicidade', language:'Idioma', unavailable:'Motor em desenvolvimento', unavailableDetail:'Esta rota já faz parte do catálogo final, mas o motor ainda não está ativo nesta compilação.', home:'Início', tools:'Ferramentas' },
  de: { siteName:'Utility Platform', tagline:'Schnelle, private Tools direkt im Browser.', search:'Suchen', searchPlaceholder:'Tools suchen…', categories:'Kategorien', allTools:'Alle Tools', calculate:'Berechnen', reset:'Zurücksetzen', result:'Ergebnis', copy:'Kopieren', copied:'Kopiert', related:'Ähnliche Tools', privacyLocal:'Läuft lokal', localDetail:'Deine Eingaben bleiben im Browser.', ad:'Anzeige', language:'Sprache', unavailable:'Engine in Entwicklung', unavailableDetail:'Diese Route gehört bereits zum finalen Katalog, die Engine ist in diesem Entwicklungsstand aber noch nicht aktiviert.', home:'Startseite', tools:'Tools' },
  fr: { siteName:'Utility Platform', tagline:'Des outils rapides et privés dans votre navigateur.', search:'Rechercher', searchPlaceholder:'Rechercher un outil…', categories:'Catégories', allTools:'Tous les outils', calculate:'Calculer', reset:'Réinitialiser', result:'Résultat', copy:'Copier', copied:'Copié', related:'Outils associés', privacyLocal:'Traitement local', localDetail:'Vos données restent dans votre navigateur.', ad:'Publicité', language:'Langue', unavailable:'Moteur en développement', unavailableDetail:'Cette route fait déjà partie du catalogue final, mais son moteur n’est pas encore activé dans cette version de développement.', home:'Accueil', tools:'Outils' },
  it: { siteName:'Utility Platform', tagline:'Strumenti veloci e privati che funzionano nel browser.', search:'Cerca', searchPlaceholder:'Cerca strumenti…', categories:'Categorie', allTools:'Tutti gli strumenti', calculate:'Calcola', reset:'Reimposta', result:'Risultato', copy:'Copia', copied:'Copiato', related:'Strumenti correlati', privacyLocal:'Funziona in locale', localDetail:'I tuoi dati restano nel browser.', ad:'Pubblicità', language:'Lingua', unavailable:'Motore in sviluppo', unavailableDetail:'Questa pagina fa già parte del catalogo finale, ma il suo motore non è ancora attivo in questa build di sviluppo.', home:'Home', tools:'Strumenti' },
  ja: { siteName:'Utility Platform', tagline:'ブラウザで動く高速でプライベートなツール。', search:'検索', searchPlaceholder:'ツールを検索…', categories:'カテゴリー', allTools:'すべてのツール', calculate:'計算', reset:'リセット', result:'結果', copy:'コピー', copied:'コピーしました', related:'関連ツール', privacyLocal:'ローカル処理', localDetail:'入力内容はブラウザ内に保持されます。', ad:'広告', language:'言語', unavailable:'エンジン開発中', unavailableDetail:'このページは最終カタログに含まれていますが、この開発ビルドでは実行エンジンがまだ有効ではありません。', home:'ホーム', tools:'ツール' },
  ar: { siteName:'Utility Platform', tagline:'أدوات سريعة وخاصة تعمل داخل متصفحك.', search:'بحث', searchPlaceholder:'ابحث عن أداة…', categories:'الفئات', allTools:'كل الأدوات', calculate:'احسب', reset:'إعادة تعيين', result:'النتيجة', copy:'نسخ', copied:'تم النسخ', related:'أدوات ذات صلة', privacyLocal:'يعمل محليًا', localDetail:'تبقى بياناتك داخل متصفحك.', ad:'إعلان', language:'اللغة', unavailable:'المحرك قيد التطوير', unavailableDetail:'هذه الصفحة جزء من الكتالوج النهائي، لكن محرك التنفيذ لم يُفعّل بعد في نسخة التطوير هذه.', home:'الرئيسية', tools:'الأدوات' },
  id: { siteName:'Utility Platform', tagline:'Alat cepat dan privat yang bekerja di browser Anda.', search:'Cari', searchPlaceholder:'Cari alat…', categories:'Kategori', allTools:'Semua alat', calculate:'Hitung', reset:'Atur ulang', result:'Hasil', copy:'Salin', copied:'Tersalin', related:'Alat terkait', privacyLocal:'Berjalan lokal', localDetail:'Data Anda tetap di browser.', ad:'Iklan', language:'Bahasa', unavailable:'Mesin sedang dikembangkan', unavailableDetail:'Rute ini sudah menjadi bagian katalog akhir, tetapi mesinnya belum diaktifkan pada build pengembangan ini.', home:'Beranda', tools:'Alat' },
  tr: { siteName:'Utility Platform', tagline:'Tarayıcınızda çalışan hızlı ve özel araçlar.', search:'Ara', searchPlaceholder:'Araç ara…', categories:'Kategoriler', allTools:'Tüm araçlar', calculate:'Hesapla', reset:'Sıfırla', result:'Sonuç', copy:'Kopyala', copied:'Kopyalandı', related:'İlgili araçlar', privacyLocal:'Yerel çalışır', localDetail:'Verileriniz tarayıcınızda kalır.', ad:'Reklam', language:'Dil', unavailable:'Motor geliştiriliyor', unavailableDetail:'Bu sayfa nihai kataloğa bağlıdır ancak motor bu geliştirme derlemesinde henüz etkin değildir.', home:'Ana sayfa', tools:'Araçlar' },
  pl: { siteName:'Utility Platform', tagline:'Szybkie i prywatne narzędzia działające w przeglądarce.', search:'Szukaj', searchPlaceholder:'Szukaj narzędzi…', categories:'Kategorie', allTools:'Wszystkie narzędzia', calculate:'Oblicz', reset:'Resetuj', result:'Wynik', copy:'Kopiuj', copied:'Skopiowano', related:'Powiązane narzędzia', privacyLocal:'Działa lokalnie', localDetail:'Twoje dane pozostają w przeglądarce.', ad:'Reklama', language:'Język', unavailable:'Silnik w budowie', unavailableDetail:'Ta trasa jest już w katalogu docelowym, ale silnik nie jest jeszcze aktywny w tej wersji deweloperskiej.', home:'Strona główna', tools:'Narzędzia' },
  ko: { siteName:'Utility Platform', tagline:'브라우저에서 작동하는 빠르고 개인적인 도구.', search:'검색', searchPlaceholder:'도구 검색…', categories:'카테고리', allTools:'모든 도구', calculate:'계산', reset:'초기화', result:'결과', copy:'복사', copied:'복사됨', related:'관련 도구', privacyLocal:'로컬 실행', localDetail:'입력 데이터는 브라우저에만 남습니다.', ad:'광고', language:'언어', unavailable:'엔진 개발 중', unavailableDetail:'이 경로는 최종 카탈로그에 포함되어 있지만 현재 개발 빌드에서는 실행 엔진이 아직 활성화되지 않았습니다.', home:'홈', tools:'도구' },
  nl: { siteName:'Utility Platform', tagline:'Snelle, private tools die in je browser werken.', search:'Zoeken', searchPlaceholder:'Zoek tools…', categories:'Categorieën', allTools:'Alle tools', calculate:'Bereken', reset:'Reset', result:'Resultaat', copy:'Kopiëren', copied:'Gekopieerd', related:'Gerelateerde tools', privacyLocal:'Werkt lokaal', localDetail:'Je gegevens blijven in je browser.', ad:'Advertentie', language:'Taal', unavailable:'Engine in ontwikkeling', unavailableDetail:'Deze route zit al in de definitieve catalogus, maar de engine is in deze ontwikkelbuild nog niet actief.', home:'Home', tools:'Tools' },
  vi: { siteName:'Utility Platform', tagline:'Công cụ nhanh và riêng tư chạy ngay trong trình duyệt.', search:'Tìm kiếm', searchPlaceholder:'Tìm công cụ…', categories:'Danh mục', allTools:'Tất cả công cụ', calculate:'Tính', reset:'Đặt lại', result:'Kết quả', copy:'Sao chép', copied:'Đã sao chép', related:'Công cụ liên quan', privacyLocal:'Xử lý cục bộ', localDetail:'Dữ liệu của bạn chỉ ở trong trình duyệt.', ad:'Quảng cáo', language:'Ngôn ngữ', unavailable:'Động cơ đang phát triển', unavailableDetail:'Trang này đã thuộc danh mục cuối cùng, nhưng động cơ chưa được bật trong bản dựng phát triển này.', home:'Trang chủ', tools:'Công cụ' },
};

export function ui(locale: LocaleId): UiCopy {
  return copy[locale];
}
