import type { SimpleResult, SimpleToolSpec, SimpleValues } from '../simple-types.ts';
const specs:Record<string,SimpleToolSpec>={};
const add=(x:SimpleToolSpec)=>specs[x.id]=x;
const ta=(key='text',label='Text',placeholder='Paste text here…')=>({key,label,type:'textarea' as const,placeholder,rows:10});
const txt=(key:string,label:string,placeholder='')=>({key,label,type:'text' as const,placeholder});
const num=(key:string,label:string,def:number)=>({key,label,type:'number' as const,defaultValue:def,step:1});
const r=(label:string,value:string|number,multiline=false):SimpleResult=>({label,value,multiline});
const input=(v:SimpleValues,k='text')=>String(v[k]??'');
const words=(x:string)=>x.trim()?x.trim().match(/[\p{L}\p{N}'’_-]+/gu)??[]:[];
const lines=(x:string)=>x.replace(/\r\n/g,'\n').split('\n');
const normalizeWords=(x:string)=>words(x).map(w=>w.toLocaleLowerCase());
const titleCase=(x:string)=>x.toLocaleLowerCase().replace(/\b([\p{L}\p{N}])/gu,m=>m.toLocaleUpperCase());
const tokens=(x:string)=>x.trim().split(/[^\p{L}\p{N}]+/u).filter(Boolean);
const camel=(x:string)=>{const a=tokens(x).map(w=>w.toLocaleLowerCase());return a.map((w,i)=>i?w[0]?.toLocaleUpperCase()+w.slice(1):w).join('')};
const secureShuffle=<T>(arr:T[]):T[]=>{const a=[...arr];for(let i=a.length-1;i>0;i--){const buf=new Uint32Array(1);crypto.getRandomValues(buf);const j=(buf[0]??0)%(i+1);[a[i],a[j]]=[a[j]!,a[i]!]}return a};
add({id:'word-counter',intro:'Count words in text.',fields:[ta()],execute:v=>[r('Words',words(input(v)).length)]});
add({id:'character-counter',intro:'Count characters with and without spaces.',fields:[ta()],execute:v=>{const x=input(v);return[r('Characters',x.length),r('Without spaces',x.replace(/\s/g,'').length)]}});
add({id:'sentence-counter',intro:'Estimate sentence count from punctuation.',fields:[ta()],execute:v=>{const x=input(v).trim();return[r('Sentences',x?Math.max(1,(x.match(/[.!?]+(?=\s|$)/g)??[]).length):0)]}});
add({id:'paragraph-counter',intro:'Count non-empty paragraphs.',fields:[ta()],execute:v=>[r('Paragraphs',input(v).trim()?input(v).trim().split(/\n\s*\n/).filter(Boolean).length:0)]});
add({id:'reading-time-calculator',intro:'Estimate silent reading time.',fields:[ta(),num('wpm','Words per minute',225)],execute:v=>{const c=words(input(v)).length,w=Number(v.wpm)||225;return[r('Reading time',`${Math.floor(c/w)} min ${Math.round((c%w)/w*60)} sec`)]}});
add({id:'speaking-time-calculator',intro:'Estimate speaking time.',fields:[ta(),num('wpm','Words per minute',130)],execute:v=>{const c=words(input(v)).length,w=Number(v.wpm)||130;return[r('Speaking time',`${Math.floor(c/w)} min ${Math.round((c%w)/w*60)} sec`)]}});
add({id:'uppercase-converter',intro:'Convert text to uppercase.',fields:[ta()],execute:v=>[r('Output',input(v).toLocaleUpperCase(),true)]});
add({id:'lowercase-converter',intro:'Convert text to lowercase.',fields:[ta()],execute:v=>[r('Output',input(v).toLocaleLowerCase(),true)]});
add({id:'title-case-converter',intro:'Convert text to title case.',fields:[ta()],execute:v=>[r('Output',titleCase(input(v)),true)]});
add({id:'sentence-case-converter',intro:'Convert text to sentence case.',fields:[ta()],execute:v=>{const x=input(v).toLocaleLowerCase();return[r('Output',x.replace(/(^\s*|[.!?]\s+)([\p{L}])/gu,(_,a,b)=>a+b.toLocaleUpperCase()),true)]}});
add({id:'camel-case-converter',intro:'Convert text to camelCase.',fields:[ta()],execute:v=>[r('Output',camel(input(v)),true)]});
add({id:'snake-case-converter',intro:'Convert text to snake_case.',fields:[ta()],execute:v=>[r('Output',tokens(input(v)).map(w=>w.toLocaleLowerCase()).join('_'),true)]});
add({id:'kebab-case-converter',intro:'Convert text to kebab-case.',fields:[ta()],execute:v=>[r('Output',tokens(input(v)).map(w=>w.toLocaleLowerCase()).join('-'),true)]});
add({id:'remove-duplicate-lines',intro:'Remove repeated lines while preserving first occurrence.',fields:[ta()],execute:v=>[r('Output',[...new Set(lines(input(v)))].join('\n'),true)]});
add({id:'sort-lines',intro:'Sort lines lexicographically.',fields:[ta()],execute:v=>[r('Output',lines(input(v)).sort((a,b)=>a.localeCompare(b)).join('\n'),true)]});
add({id:'reverse-text',intro:'Reverse Unicode characters.',fields:[ta()],execute:v=>[r('Output',[...input(v)].reverse().join(''),true)]});
add({id:'reverse-lines',intro:'Reverse line order.',fields:[ta()],execute:v=>[r('Output',lines(input(v)).reverse().join('\n'),true)]});
add({id:'remove-empty-lines',intro:'Remove blank lines.',fields:[ta()],execute:v=>[r('Output',lines(input(v)).filter(x=>x.trim()).join('\n'),true)]});
add({id:'remove-extra-spaces',intro:'Collapse repeated whitespace.',fields:[ta()],execute:v=>[r('Output',input(v).replace(/[ \t]+/g,' ').replace(/ *\n */g,'\n').trim(),true)]});
add({id:'trim-lines',intro:'Trim whitespace from every line.',fields:[ta()],execute:v=>[r('Output',lines(input(v)).map(x=>x.trim()).join('\n'),true)]});
add({id:'find-and-replace',intro:'Find and replace literal text.',fields:[ta(),txt('find','Find'),txt('replace','Replace with')],execute:v=>{const f=input(v,'find');if(!f)throw new Error('Find value cannot be empty');return[r('Output',input(v).split(f).join(input(v,'replace')),true)]}});
add({id:'text-diff',intro:'Compare two texts line by line.',fields:[ta('a','Text A'),ta('b','Text B')],execute:v=>{const a=lines(input(v,'a')),b=lines(input(v,'b')),out:string[]=[];const m=Math.max(a.length,b.length);for(let i=0;i<m;i++){if(a[i]===b[i])out.push(`  ${a[i]??''}`);else{if(a[i]!==undefined)out.push(`- ${a[i]}`);if(b[i]!==undefined)out.push(`+ ${b[i]}`)}}return[r('Diff',out.join('\n'),true)]}});
add({id:'remove-line-breaks',intro:'Replace line breaks with spaces.',fields:[ta()],execute:v=>[r('Output',input(v).replace(/\s*\r?\n\s*/g,' ').trim(),true)]});
add({id:'add-line-numbers',intro:'Prefix every line with a number.',fields:[ta()],execute:v=>[r('Output',lines(input(v)).map((x,i)=>`${i+1}. ${x}`).join('\n'),true)]});
add({id:'randomize-lines',intro:'Shuffle lines using browser cryptographic randomness.',fields:[ta()],execute:v=>[r('Output',secureShuffle(lines(input(v))).join('\n'),true)]});
add({id:'alphabetize-list',intro:'Alphabetize one item per line.',fields:[ta()],execute:v=>[r('Output',lines(input(v)).filter(Boolean).sort((a,b)=>a.localeCompare(b,undefined,{sensitivity:'base'})).join('\n'),true)]});
add({id:'word-frequency-counter',intro:'Count each word and sort by frequency.',fields:[ta()],execute:v=>{const m=new Map<string,number>();normalizeWords(input(v)).forEach(w=>m.set(w,(m.get(w)??0)+1));return[r('Frequency',[...m].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).map(([w,c])=>`${w}: ${c}`).join('\n'),true)]}});
add({id:'unique-word-counter',intro:'Count unique words.',fields:[ta()],execute:v=>[r('Unique words',new Set(normalizeWords(input(v))).size)]});
add({id:'duplicate-word-finder',intro:'Find words that appear more than once.',fields:[ta()],execute:v=>{const m=new Map<string,number>();normalizeWords(input(v)).forEach(w=>m.set(w,(m.get(w)??0)+1));return[r('Duplicates',[...m].filter(([,c])=>c>1).map(([w,c])=>`${w} (${c})`).join(', ')||'None',true)]}});
add({id:'text-to-slug',intro:'Create a URL-friendly slug.',fields:[ta()],execute:v=>[r('Slug',input(v).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''))]});
export const textToolIds=()=>Object.keys(specs);
export const getTextSpec=(id:string)=>specs[id];
export const runTextTool=(id:string,v:SimpleValues)=>{const x=specs[id];if(!x)throw new Error(`Text tool not implemented: ${id}`);return x.execute(v)};
