import type { FileToolField, FileToolResult, FileToolSpec, FileToolValues } from '../file-types.ts';
const specs:Record<string,FileToolSpec>={};const add=(x:FileToolSpec)=>specs[x.id]=x;
const file=(multiple=false,accept='image/*'):FileToolField=>({key:'file',label:multiple?'Images':'Image',type:'file',accept,multiple,required:true});
const num=(key:string,label:string,d:number,min?:number,max?:number):FileToolField=>({key,label,type:'number',defaultValue:d,step:1,min,max});
const color=(key:string,label:string,d:string):FileToolField=>({key,label,type:'color',defaultValue:d});
const sel=(key:string,label:string,options:{value:string;label:string}[],d?:string):FileToolField=>({key,label,type:'select',options,defaultValue:d??options[0]?.value});
const text=(key:string,label:string,placeholder=''):FileToolField=>({key,label,type:'textarea',placeholder,rows:8});
const out=(label:string,value:string|number):FileToolResult=>({label,value,multiline:typeof value==='string'&&value.length>120});
const fOut=(label:string,blob:Blob,filename:string,preview=true):FileToolResult=>({kind:'file',label,blob,filename,preview});
const one=(v:FileToolValues):File=>{const x=v.file;if(!(x instanceof File))throw new Error('Choose an image file');return x};
const files=(v:FileToolValues):File[]=>Array.isArray(v.file)?v.file:(v.file instanceof File?[v.file]:[]);
const n=(v:FileToolValues,k:string)=>Number(v[k]??0);
const mimeExt=(mime:string)=>mime==='image/png'?'png':mime==='image/webp'?'webp':mime==='image/svg+xml'?'svg':'jpg';
async function heicIfNeeded(blob:Blob):Promise<Blob>{const name=(blob as File).name?.toLowerCase()??'';if(blob.type==='image/heic'||blob.type==='image/heif'||/\.(heic|heif)$/.test(name)){const {default:heic2any}=await import('heic2any');const converted=await heic2any({blob,toType:'image/jpeg',quality:.95});return Array.isArray(converted)?converted[0]!:converted}return blob}
async function bitmap(blob:Blob):Promise<ImageBitmap>{return createImageBitmap(await heicIfNeeded(blob))}
function canvas(w:number,h:number){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));const ctx=c.getContext('2d',{willReadFrequently:true});if(!ctx)throw new Error('Canvas is not available');return{c,ctx}}
function toBlob(c:HTMLCanvasElement,type='image/png',quality=.92):Promise<Blob>{return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Could not encode image')),type,quality))}
async function drawOriginal(blob:Blob){const b=await bitmap(blob);const {c,ctx}=canvas(b.width,b.height);ctx.drawImage(b,0,0);b.close();return{c,ctx}}
async function encode(blob:Blob,type:string,quality=.92){const {c}=await drawOriginal(blob);return toBlob(c,type,quality)}
function targetSize(w:number,h:number,targetW:number,targetH:number){if(targetW<=0&&targetH<=0)return[w,h];if(targetW<=0)return[Math.round(w*targetH/h),targetH];if(targetH<=0)return[targetW,Math.round(h*targetW/w)];return[targetW,targetH] as const}
async function resizeBlob(blob:Blob,targetW:number,targetH:number,type='image/png',quality=.92){const b=await bitmap(blob);const [w,h]=targetSize(b.width,b.height,targetW,targetH);const {c,ctx}=canvas(w,h);ctx.imageSmoothingQuality='high';ctx.drawImage(b,0,0,w,h);b.close();return toBlob(c,type,quality)}
async function coverBlob(blob:Blob,w:number,h:number,type='image/jpeg',quality=.92){const b=await bitmap(blob);const scale=Math.max(w/b.width,h/b.height),sw=w/scale,sh=h/scale,sx=(b.width-sw)/2,sy=(b.height-sh)/2;const {c,ctx}=canvas(w,h);ctx.drawImage(b,sx,sy,sw,sh,0,0,w,h);b.close();return toBlob(c,type,quality)}
add({id:'compress-image',intro:'Compress an image locally by re-encoding it as JPEG or WebP.',fields:[file(),sel('format','Output format',[{value:'image/webp',label:'WebP'},{value:'image/jpeg',label:'JPEG'}],'image/webp'),num('quality','Quality %',80,1,100)],execute:async v=>{const src=one(v),type=String(v.format),blob=await encode(src,type,n(v,'quality')/100);return[out('Original size',`${(src.size/1024).toFixed(1)} KB`),out('Compressed size',`${(blob.size/1024).toFixed(1)} KB`),fOut('Compressed image',blob,`compressed.${mimeExt(type)}`)]}});
add({id:'resize-image',intro:'Resize an image to explicit dimensions; use 0 for one dimension to preserve aspect ratio.',fields:[file(),num('width','Width (px)',1200,0),num('height','Height (px)',0,0),sel('format','Output format',[{value:'image/png',label:'PNG'},{value:'image/jpeg',label:'JPEG'},{value:'image/webp',label:'WebP'}],'image/png')],execute:async v=>{const type=String(v.format),blob=await resizeBlob(one(v),n(v,'width'),n(v,'height'),type);return[fOut('Resized image',blob,`resized.${mimeExt(type)}`)]}});
add({id:'crop-image',intro:'Crop an image using pixel coordinates. Width/height 0 extend to the image edge.',fields:[file(),num('x','X (px)',0,0),num('y','Y (px)',0,0),num('width','Width (px)',0,0),num('height','Height (px)',0,0)],execute:async v=>{const b=await bitmap(one(v)),x=Math.min(b.width,Math.max(0,n(v,'x'))),y=Math.min(b.height,Math.max(0,n(v,'y'))),w=n(v,'width')||b.width-x,h=n(v,'height')||b.height-y,{c,ctx}=canvas(Math.min(w,b.width-x),Math.min(h,b.height-y));ctx.drawImage(b,x,y,c.width,c.height,0,0,c.width,c.height);b.close();return[fOut('Cropped image',await toBlob(c,'image/png'),'cropped.png')]}});
add({id:'rotate-image',intro:'Rotate an image clockwise.',fields:[file(),num('angle','Angle (degrees)',90)],execute:async v=>{const b=await bitmap(one(v)),a=n(v,'angle')*Math.PI/180,cos=Math.abs(Math.cos(a)),sin=Math.abs(Math.sin(a)),{c,ctx}=canvas(b.width*cos+b.height*sin,b.width*sin+b.height*cos);ctx.translate(c.width/2,c.height/2);ctx.rotate(a);ctx.drawImage(b,-b.width/2,-b.height/2);b.close();return[fOut('Rotated image',await toBlob(c),'rotated.png')]}});
add({id:'flip-image',intro:'Flip an image horizontally or vertically.',fields:[file(),sel('direction','Direction',[{value:'horizontal',label:'Horizontal'},{value:'vertical',label:'Vertical'}])],execute:async v=>{const b=await bitmap(one(v)),{c,ctx}=canvas(b.width,b.height);ctx.translate(String(v.direction)==='horizontal'?b.width:0,String(v.direction)==='vertical'?b.height:0);ctx.scale(String(v.direction)==='horizontal'?-1:1,String(v.direction)==='vertical'?-1:1);ctx.drawImage(b,0,0);b.close();return[fOut('Flipped image',await toBlob(c),'flipped.png')]}});
for(const [id,type] of [['jpg-to-png','image/png'],['webp-to-png','image/png'],['png-to-jpg','image/jpeg'],['webp-to-jpg','image/jpeg'],['jpg-to-webp','image/webp'],['png-to-webp','image/webp']] as const)add({id,intro:`Convert an image to ${mimeExt(type).toUpperCase()} locally.`,fields:[file(),num('quality','Quality %',92,1,100)],execute:async v=>{const blob=await encode(one(v),type,n(v,'quality')/100);return[fOut('Converted image',blob,`converted.${mimeExt(type)}`)]}});
add({id:'heic-to-jpg',intro:'Convert HEIC/HEIF to JPEG entirely in the browser.',fields:[file(false,'.heic,.heif,image/heic,image/heif'),num('quality','JPEG quality %',90,1,100)],execute:async v=>{const {default:heic2any}=await import('heic2any');const x=await heic2any({blob:one(v),toType:'image/jpeg',quality:n(v,'quality')/100});const blob=Array.isArray(x)?x[0]!:x;return[fOut('JPEG image',blob,'converted.jpg')]}});
for(const [id,type] of [['svg-to-png','image/png'],['svg-to-jpg','image/jpeg']] as const)add({id,intro:`Render SVG as ${mimeExt(type).toUpperCase()}.`,fields:[file(false,'.svg,image/svg+xml'),num('width','Output width (0 = original)',0,0),num('height','Output height (0 = original)',0,0)],execute:async v=>{const blob=await resizeBlob(one(v),n(v,'width'),n(v,'height'),type);return[fOut('Rendered image',blob,`rendered.${mimeExt(type)}`)]}});
add({id:'image-to-base64',intro:'Convert an image file to a Base64 data URL.',fields:[file()],execute:async v=>{const f=one(v),data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(f)});return[out('Data URL',data)]}});
add({id:'base64-to-image',intro:'Convert an image data URL or Base64 string to a downloadable file.',fields:[text('base64','Base64 / data URL')],execute:async v=>{let raw=String(v.base64??'').trim(),mime='image/png';const m=raw.match(/^data:([^;]+);base64,(.*)$/s);if(m){mime=m[1]!;raw=m[2]!}const bin=atob(raw.replace(/\s/g,'')),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0)),blob=new Blob([bytes],{type:mime});return[fOut('Decoded image',blob,`decoded.${mimeExt(mime)}`)]}});
add({id:'remove-exif-metadata',intro:'Strip image metadata by decoding and re-encoding pixel data.',fields:[file(),sel('format','Output format',[{value:'image/jpeg',label:'JPEG'},{value:'image/png',label:'PNG'},{value:'image/webp',label:'WebP'}],'image/jpeg')],execute:async v=>{const type=String(v.format),blob=await encode(one(v),type,.95);return[fOut('Metadata-stripped image',blob,`clean.${mimeExt(type)}`)]}});
add({id:'exif-viewer',intro:'Inspect EXIF, XMP and other supported metadata locally.',fields:[file()],execute:async v=>{const ExifReader=(await import('exifreader')).default;const tags=await ExifReader.load(one(v));const clean=Object.fromEntries(Object.entries(tags).filter(([k])=>!['Thumbnail','MakerNote'].includes(k)).slice(0,250).map(([k,val]:any)=>[k,val?.description??val?.value??String(val)]));return[out('Metadata',JSON.stringify(clean,null,2))]}});
add({id:'change-image-dpi',intro:'Set JPEG X/Y resolution metadata without uploading the image.',fields:[file(false,'.jpg,.jpeg,image/jpeg'),num('dpi','DPI',300,1,2400)],execute:async v=>{const src=one(v);if(src.type&&src.type!=='image/jpeg'&&!/\.jpe?g$/i.test(src.name))throw new Error('DPI metadata editing currently supports JPEG files');const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(src)});const mod=await import('piexifjs');const piexif=mod.default;let exif:any;try{exif=piexif.load(data)}catch{exif={'0th':{},Exif:{},GPS:{},Interop:{},'1st':{},thumbnail:null}}const dpi=Math.max(1,Math.round(n(v,'dpi')));exif['0th'][piexif.ImageIFD.XResolution]=[dpi,1];exif['0th'][piexif.ImageIFD.YResolution]=[dpi,1];exif['0th'][piexif.ImageIFD.ResolutionUnit]=2;const outData=piexif.insert(piexif.dump(exif),data),bin=atob(outData.split(',')[1]!),blob=new Blob([Uint8Array.from(bin,c=>c.charCodeAt(0))],{type:'image/jpeg'});return[fOut('JPEG with updated DPI',blob,'dpi-updated.jpg')]}});
add({id:'image-dimensions-checker',intro:'Read image pixel dimensions locally.',fields:[file()],execute:async v=>{const b=await bitmap(one(v));const result=[out('Width',`${b.width} px`),out('Height',`${b.height} px`),out('Megapixels',((b.width*b.height)/1e6).toFixed(2))];b.close();return result}});
add({id:'image-file-size-estimator',intro:'Estimate output size by re-encoding the image with chosen format and quality.',fields:[file(),sel('format','Format',[{value:'image/webp',label:'WebP'},{value:'image/jpeg',label:'JPEG'}]),num('quality','Quality %',80,1,100)],execute:async v=>{const blob=await encode(one(v),String(v.format),n(v,'quality')/100);return[out('Estimated encoded size',`${(blob.size/1024).toFixed(1)} KB`)]}});
add({id:'add-image-border',intro:'Add a solid border around an image.',fields:[file(),num('size','Border size (px)',20,0,1000),color('color','Border color','#FFFFFF')],execute:async v=>{const b=await bitmap(one(v)),s=Math.max(0,n(v,'size')),{c,ctx}=canvas(b.width+2*s,b.height+2*s);ctx.fillStyle=String(v.color);ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(b,s,s);b.close();return[fOut('Bordered image',await toBlob(c),'bordered.png')]}});
add({id:'round-image-corners',intro:'Round image corners and export as transparent PNG.',fields:[file(),num('radius','Radius (px)',40,0,2000)],execute:async v=>{const b=await bitmap(one(v)),{c,ctx}=canvas(b.width,b.height),rad=Math.min(n(v,'radius'),b.width/2,b.height/2);ctx.beginPath();ctx.roundRect(0,0,b.width,b.height,rad);ctx.clip();ctx.drawImage(b,0,0);b.close();return[fOut('Rounded image',await toBlob(c),'rounded.png')]}});
add({id:'grayscale-image',intro:'Convert an image to grayscale.',fields:[file()],execute:async v=>{const b=await bitmap(one(v)),{c,ctx}=canvas(b.width,b.height);ctx.filter='grayscale(1)';ctx.drawImage(b,0,0);b.close();return[fOut('Grayscale image',await toBlob(c),'grayscale.png')]}});
add({id:'image-opacity-tool',intro:'Apply opacity and export a transparent PNG.',fields:[file(),num('opacity','Opacity %',60,0,100)],execute:async v=>{const b=await bitmap(one(v)),{c,ctx}=canvas(b.width,b.height);ctx.globalAlpha=n(v,'opacity')/100;ctx.drawImage(b,0,0);b.close();return[fOut('Image with opacity',await toBlob(c),'opacity.png')]}});
add({id:'pixelate-image',intro:'Pixelate an image using a configurable block size.',fields:[file(),num('block','Block size (px)',12,2,200)],execute:async v=>{const b=await bitmap(one(v)),block=Math.max(2,n(v,'block')),smallW=Math.max(1,Math.round(b.width/block)),smallH=Math.max(1,Math.round(b.height/block)),tmp=canvas(smallW,smallH);tmp.ctx.drawImage(b,0,0,smallW,smallH);const {c,ctx}=canvas(b.width,b.height);ctx.imageSmoothingEnabled=false;ctx.drawImage(tmp.c,0,0,b.width,b.height);b.close();return[fOut('Pixelated image',await toBlob(c),'pixelated.png')]}});
add({id:'blur-image',intro:'Blur an image using the Canvas blur filter.',fields:[file(),num('radius','Blur radius (px)',8,0,100)],execute:async v=>{const b=await bitmap(one(v)),{c,ctx}=canvas(b.width,b.height);ctx.filter=`blur(${n(v,'radius')}px)`;ctx.drawImage(b,0,0);b.close();return[fOut('Blurred image',await toBlob(c),'blurred.png')]}});
add({id:'image-color-picker',intro:'Read the pixel color at an X/Y coordinate.',fields:[file(),num('x','X (px)',0,0),num('y','Y (px)',0,0)],execute:async v=>{const {c,ctx}=await drawOriginal(one(v)),px=ctx.getImageData(Math.min(c.width-1,Math.max(0,n(v,'x'))),Math.min(c.height-1,Math.max(0,n(v,'y'))),1,1).data,hex='#'+[px[0],px[1],px[2]].map(z=>z!.toString(16).padStart(2,'0')).join('').toUpperCase();return[out('HEX',hex),out('RGB',`rgb(${px[0]}, ${px[1]}, ${px[2]})`)]}});
add({id:'extract-colors-from-image',intro:'Extract dominant approximate colors by sampled color buckets.',fields:[file(),num('count','Color count',5,1,12)],execute:async v=>{const b=await bitmap(one(v)),scale=Math.min(1,160/Math.max(b.width,b.height)),{c,ctx}=canvas(b.width*scale,b.height*scale);ctx.drawImage(b,0,0,c.width,c.height);b.close();const data=ctx.getImageData(0,0,c.width,c.height).data,m=new Map<string,number>();for(let i=0;i<data.length;i+=16){if((data[i+3]??0)<128)continue;const q=(z:number)=>Math.min(255,Math.round(z/32)*32),key=`${q(data[i]!)},${q(data[i+1]!)},${q(data[i+2]!)}`;m.set(key,(m.get(key)??0)+1)}return[...m].sort((a,b)=>b[1]-a[1]).slice(0,Math.max(1,n(v,'count'))).map(([k],i)=>{const [r,g,b]=k.split(',').map(Number),hex='#'+[r,g,b].map(z=>z!.toString(16).padStart(2,'0')).join('').toUpperCase();return out(`Color ${i+1}`,hex)})}});
add({id:'batch-image-resizer',intro:'Resize multiple images locally and download each result.',fields:[file(true),num('width','Width (px)',1200,1),num('height','Height (0 = preserve aspect)',0,0)],execute:async v=>{const xs=files(v);if(!xs.length)throw new Error('Choose one or more images');const outputs:FileToolResult[]=[];for(const [i,src] of xs.entries()){const blob=await resizeBlob(src,n(v,'width'),n(v,'height'),'image/jpeg',.92);outputs.push(fOut(`Image ${i+1}`,blob,`${src.name.replace(/\.[^.]+$/,'')}-resized.jpg`))}return outputs}});
for(const [id,w,h,name] of [['profile-picture-cropper',1080,1080,'profile'],['youtube-thumbnail-resizer',1280,720,'youtube-thumbnail'],['instagram-image-resizer',1080,1080,'instagram'],['instagram-story-resizer',1080,1920,'instagram-story'],['opengraph-image-resizer',1200,630,'opengraph']] as const)add({id,intro:`Center-crop and resize to ${w}×${h}.`,fields:[file()],execute:async v=>[fOut('Resized image',await coverBlob(one(v),w,h,'image/jpeg',.92),`${name}.jpg`)]});
export const imageToolIds=()=>Object.keys(specs);export const getImageSpec=(id:string)=>specs[id];export const runImageTool=(id:string,v:FileToolValues)=>{const tool=specs[id];if(!tool)throw new Error(`Image tool not implemented: ${id}`);return tool.execute(v)};
