import type { FileToolResult, FileToolSpec, FileToolValues } from '../file-types.ts';
type V=[number,number,number];type Tri=[V,V,V];const specs:Record<string,FileToolSpec>={};const add=(x:FileToolSpec)=>specs[x.id]=x;const field={key:'file',label:'STL file',type:'file' as const,accept:'.stl,model/stl,application/sla',required:true};const one=(v:FileToolValues)=>{const f=v.file;if(!(f instanceof File)||!f.size)throw new Error('Choose an STL file');return f};const out=(label:string,value:string|number):FileToolResult=>({label,value});const fOut=(label:string,blob:Blob,filename:string):FileToolResult=>({kind:'file',label,blob,filename,preview:true});
function parseBinary(buf:ArrayBuffer):Tri[]{const dv=new DataView(buf),count=dv.getUint32(80,true);if(84+count*50>buf.byteLength)throw new Error('Invalid binary STL');const tris:Tri[]=[];let o=84;for(let i=0;i<count;i++,o+=50){const a:V=[dv.getFloat32(o+12,true),dv.getFloat32(o+16,true),dv.getFloat32(o+20,true)],b:V=[dv.getFloat32(o+24,true),dv.getFloat32(o+28,true),dv.getFloat32(o+32,true)],c:V=[dv.getFloat32(o+36,true),dv.getFloat32(o+40,true),dv.getFloat32(o+44,true)];tris.push([a,b,c])}return tris}
function parseAscii(text:string):Tri[]{const vals=[...text.matchAll(/vertex\s+([-+\deE.]+)\s+([-+\deE.]+)\s+([-+\deE.]+)/gi)].map(m=>[Number(m[1]),Number(m[2]),Number(m[3])] as V),tris:Tri[]=[];for(let i=0;i+2<vals.length;i+=3)tris.push([vals[i]!,vals[i+1]!,vals[i+2]!]);if(!tris.length)throw new Error('No triangles found in STL');return tris}
async function parse(f:File){const buf=await f.arrayBuffer();try{if(buf.byteLength>=84){const n=new DataView(buf).getUint32(80,true);if(84+n*50===buf.byteLength)return parseBinary(buf)}}catch{}return parseAscii(new TextDecoder().decode(buf))}
function bounds(t:Tri[]){const min:V=[Infinity,Infinity,Infinity],max:V=[-Infinity,-Infinity,-Infinity];for(const tri of t)for(const v of tri){min[0]=Math.min(min[0],v[0]);min[1]=Math.min(min[1],v[1]);min[2]=Math.min(min[2],v[2]);max[0]=Math.max(max[0],v[0]);max[1]=Math.max(max[1],v[1]);max[2]=Math.max(max[2],v[2]);}return{min,max,size:[max[0]-min[0],max[1]-min[1],max[2]-min[2]] as V}}
function volume(ts:Tri[]){let sum=0;for(const [a,b,c] of ts)sum+=(a[0]*(b[1]*c[2]-b[2]*c[1])-a[1]*(b[0]*c[2]-b[2]*c[0])+a[2]*(b[0]*c[1]-b[1]*c[0]))/6;return Math.abs(sum)}
add({id:'stl-dimensions-checker',intro:'Read STL dimensions locally.',fields:[field],execute:async v=>{const t=await parse(one(v)),b=bounds(t);return[out('X',b.size[0].toFixed(3)+' mm'),out('Y',b.size[1].toFixed(3)+' mm'),out('Z',b.size[2].toFixed(3)+' mm'),out('Triangles',t.length)]}});
add({id:'stl-volume-calculator',intro:'Calculate enclosed STL mesh volume using signed tetrahedra.',fields:[field],execute:async v=>{const t=await parse(one(v)),mm3=volume(t);return[out('Volume',mm3.toFixed(3)+' mm³'),out('Volume', (mm3/1000).toFixed(3)+' cm³'),out('Triangles',t.length)]}});
add({id:'stl-viewer',intro:'Generate a lightweight isometric wireframe preview of an STL file.',fields:[field],execute:async v=>{const t=await parse(one(v)),b=bounds(t),c=document.createElement('canvas');c.width=900;c.height=650;const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas unavailable');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);const project=(p:V):[number,number]=>{const x=p[0]-(b.min[0]+b.max[0])/2,y=p[1]-(b.min[1]+b.max[1])/2,z=p[2]-(b.min[2]+b.max[2])/2;return[x-y*.55,(x+y)*.28-z]};const pts=t.flatMap(q=>q).map(project),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),spanX=Math.max(...xs)-Math.min(...xs)||1,spanY=Math.max(...ys)-Math.min(...ys)||1,scale=Math.min(800/spanX,550/spanY),cx=(Math.min(...xs)+Math.max(...xs))/2,cy=(Math.min(...ys)+Math.max(...ys))/2;ctx.strokeStyle='#111827';ctx.globalAlpha=.35;ctx.lineWidth=.7;for(const tri of t.slice(0,30000)){ctx.beginPath();tri.map(project).forEach((p,i)=>{const x=(p[0]-cx)*scale+c.width/2,y=(p[1]-cy)*scale+c.height/2;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});const p=project(tri[0]);ctx.lineTo((p[0]-cx)*scale+c.width/2,(p[1]-cy)*scale+c.height/2);ctx.stroke()}const blob=await new Promise<Blob>((res,rej)=>c.toBlob(x=>x?res(x):rej(new Error('Preview encode failed')),'image/png'));return[fOut('STL preview',blob,'stl-preview.png'),out('Triangles',t.length)]}});
export const makerFileToolIds=()=>Object.keys(specs);export const getMakerFileSpec=(id:string)=>specs[id];
