import type { FileToolField, FileToolResult, FileToolSpec, FileToolValues } from '../file-types.ts';
const specs:Record<string,FileToolSpec>={}; const add=(s:FileToolSpec)=>specs[s.id]=s;
const text=(key:string,label:string,d='',area=false):FileToolField=>({key,label,type:area?'textarea':'text',defaultValue:d,rows:area?6:undefined});
const num=(key:string,label:string,d:number,min?:number,max?:number):FileToolField=>({key,label,type:'number',defaultValue:d,min,max,step:1});
const color=(key:string,label:string,d:string):FileToolField=>({key,label,type:'color',defaultValue:d});
const file=(key='file',label='Image',accept='image/*'):FileToolField=>({key,label,type:'file',accept,required:true});
const sel=(key:string,label:string,opts:{value:string;label:string}[],d?:string):FileToolField=>({key,label,type:'select',options:opts,defaultValue:d??opts[0]?.value});
const out=(label:string,value:string|number):FileToolResult=>({label,value,multiline:typeof value==='string'&&value.length>100});
const fOut=(label:string,blob:Blob,filename:string,preview=true):FileToolResult=>({kind:'file',label,blob,filename,preview});
const s=(v:FileToolValues,k:string)=>String(v[k]??''); const n=(v:FileToolValues,k:string)=>Number(v[k]??0);
const getFile=(v:FileToolValues,k='file')=>{const x=v[k];if(!(x instanceof File)||!x.size)throw new Error(`Choose ${k==='file'?'an image':'a file'}`);return x};
function dataUrlBlob(dataUrl:string){const [head,raw]=dataUrl.split(',');if(!raw)throw new Error('Invalid generated image');const mime=(head??'').match(/^data:([^;]+)/)?.[1]??'image/png';const bytes=Uint8Array.from(atob(raw),c=>c.charCodeAt(0));return new Blob([bytes],{type:mime});}
async function qrPng(payload:string,v:FileToolValues){if(!payload)throw new Error('Enter content for the QR code');const QRCode=(await import('qrcode')).default;const url=await QRCode.toDataURL(payload,{width:Math.max(128,n(v,'size')||512),margin:Math.max(0,n(v,'margin')||2),errorCorrectionLevel:s(v,'level')||'M',color:{dark:s(v,'dark')||'#000000',light:s(v,'light')||'#ffffff'}});return dataUrlBlob(url)}
const qrFields=(payload:FileToolField[])=>[...payload,num('size','Size (px)',512,128,2048),num('margin','Margin',2,0,20),sel('level','Error correction',[{value:'L',label:'L'},{value:'M',label:'M'},{value:'Q',label:'Q'},{value:'H',label:'H'}],'M'),color('dark','Foreground','#000000'),color('light','Background','#ffffff')];
function qr(id:string,intro:string,fields:FileToolField[],payload:(v:FileToolValues)=>string){add({id,intro,fields:qrFields(fields),execute:async v=>[fOut('QR code',await qrPng(payload(v),v),`${id}.png`)]})}
qr('url-qr-generator','Create a QR code for a URL.',[text('url','URL','https://example.com')],v=>s(v,'url'));
qr('text-qr-generator','Create a QR code from arbitrary text.',[text('text','Text','Hello world',true)],v=>s(v,'text'));
qr('wi-fi-qr-generator','Create a Wi-Fi QR code.',[text('ssid','Network name'),text('password','Password'),sel('security','Security',[{value:'WPA',label:'WPA/WPA2'},{value:'WEP',label:'WEP'},{value:'nopass',label:'Open'}],'WPA')],v=>`WIFI:T:${s(v,'security')};S:${s(v,'ssid').replace(/([\\;,:"])/g,'\\$1')};P:${s(v,'password').replace(/([\\;,:"])/g,'\\$1')};;`);
qr('email-qr-generator','Create an email QR code.',[text('email','Email'),text('subject','Subject'),text('body','Body','',true)],v=>`mailto:${s(v,'email')}?subject=${encodeURIComponent(s(v,'subject'))}&body=${encodeURIComponent(s(v,'body'))}`);
qr('phone-qr-generator','Create a phone-call QR code.',[text('phone','Phone number','+390000000000')],v=>`tel:${s(v,'phone')}`);
qr('sms-qr-generator','Create an SMS QR code.',[text('phone','Phone number'),text('message','Message','',true)],v=>`SMSTO:${s(v,'phone')}:${s(v,'message')}`);
qr('whatsapp-qr-generator','Create a WhatsApp chat QR code.',[text('phone','Phone number with country code'),text('message','Message','',true)],v=>`https://wa.me/${s(v,'phone').replace(/\D/g,'')}?text=${encodeURIComponent(s(v,'message'))}`);
qr('vcard-qr-generator','Create a vCard contact QR code.',[text('name','Full name'),text('phone','Phone'),text('email','Email'),text('org','Organization')],v=>`BEGIN:VCARD\nVERSION:3.0\nFN:${s(v,'name')}\nTEL:${s(v,'phone')}\nEMAIL:${s(v,'email')}\nORG:${s(v,'org')}\nEND:VCARD`);
qr('location-qr-generator','Create a geographic-coordinate QR code.',[text('lat','Latitude','43.7696'),text('lng','Longitude','11.2558')],v=>`geo:${s(v,'lat')},${s(v,'lng')}`);
qr('calendar-event-qr-generator','Create an iCalendar event QR code.',[text('title','Event title'),text('start','Start UTC','20260912T120000Z'),text('end','End UTC','20260912T130000Z'),text('location','Location')],v=>`BEGIN:VEVENT\nSUMMARY:${s(v,'title')}\nDTSTART:${s(v,'start')}\nDTEND:${s(v,'end')}\nLOCATION:${s(v,'location')}\nEND:VEVENT`);
qr('qr-color-customizer','Create a QR code with custom foreground/background colors.',[text('text','Content','https://example.com',true)],v=>s(v,'text'));
add({id:'qr-with-logo',intro:'Create a QR code and place a logo in its center.',fields:[...qrFields([text('text','Content','https://example.com',true)]),file('logo','Logo image')],execute:async v=>{const blob=await qrPng(s(v,'text'),{...v,level:'H'}),qr=await createImageBitmap(blob),logo=await createImageBitmap(getFile(v,'logo')),c=document.createElement('canvas');c.width=qr.width;c.height=qr.height;const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas unavailable');ctx.drawImage(qr,0,0);const side=Math.round(qr.width*.2),x=(qr.width-side)/2,y=(qr.height-side)/2;ctx.fillStyle='#fff';ctx.fillRect(x-8,y-8,side+16,side+16);ctx.drawImage(logo,x,y,side,side);qr.close();logo.close();const output=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Could not encode image')),'image/png'));return[fOut('QR with logo',output,'qr-with-logo.png')]}});
async function decode(v:FileToolValues,qrOnly=false){const file=getFile(v),url=URL.createObjectURL(file);try{const z=await import('@zxing/browser');const reader=qrOnly?new z.BrowserQRCodeReader():new z.BrowserMultiFormatReader();const result=await reader.decodeFromImageUrl(url);return[out('Decoded content',result.getText()),out('Format',String(result.getBarcodeFormat?.()??''))]}finally{URL.revokeObjectURL(url)}}
add({id:'qr-reader-from-image',intro:'Read a QR code from an uploaded image.',fields:[file()],execute:v=>decode(v,true)});
function barcode(id:string,format:string,label:string){add({id,intro:`Generate a ${label} barcode locally.`,fields:[text('value','Value',format==='EAN13'?'5901234123457':format==='EAN8'?'96385074':format==='UPC'?'012345678905':'1234567890'),num('width','Bar width',2,1,8),num('height','Height',100,20,400),color('line','Bar color','#000000'),color('background','Background','#ffffff')],execute:async v=>{const JsBarcode=(await import('jsbarcode')).default,svg=document.createElementNS('http://www.w3.org/2000/svg','svg');try{JsBarcode(svg,s(v,'value'),{format,width:n(v,'width'),height:n(v,'height'),lineColor:s(v,'line'),background:s(v,'background'),displayValue:true,margin:10});}catch(e){throw new Error(e instanceof Error?e.message:'Invalid barcode value')}const text=new XMLSerializer().serializeToString(svg),blob=new Blob([text],{type:'image/svg+xml'});return[fOut(label,blob,`${id}.svg`,true)]}})}
barcode('barcode-generator','CODE128','Barcode'); barcode('code-128-generator','CODE128','Code 128'); barcode('ean-13-generator','EAN13','EAN-13'); barcode('ean-8-generator','EAN8','EAN-8'); barcode('upc-a-generator','UPC','UPC-A'); barcode('code-39-generator','CODE39','Code 39'); barcode('isbn-barcode-generator','EAN13','ISBN / EAN-13');
add({id:'barcode-reader',intro:'Read a supported 1D/2D barcode from an uploaded image.',fields:[file()],execute:v=>decode(v,false)});
export const qrBarcodeToolIds=()=>Object.keys(specs); export const getQrBarcodeSpec=(id:string)=>specs[id];
