import type { CalculatorResult, CalculatorSpec, CalculatorValues } from './types.ts';

const n = (v: CalculatorValues, key: string): number => {
  const value = Number(v[key]);
  if (!Number.isFinite(value)) throw new Error(`Invalid value: ${key}`);
  return value;
};
const s = (v: CalculatorValues, key: string): string => String(v[key] ?? '').trim();
const nz = (x: number, label = 'value'): number => { if (x === 0) throw new Error(`${label} cannot be zero`); return x; };
const result = (label: string, value: string | number, unit?: string, maximumFractionDigits = 6): CalculatorResult => ({ label, value, unit, maximumFractionDigits });
const num = (key: string, label: string, defaultValue?: number, step = 0.01) => ({ key, label, type: 'number' as const, defaultValue, step });
const text = (key: string, label: string, placeholder?: string) => ({ key, label, type: 'text' as const, placeholder });
const select = (key: string, label: string, options: { value: string; label: string }[], defaultValue?: string) => ({ key, label, type: 'select' as const, options, defaultValue });
const list = (raw: string): number[] => {
  const values = raw.split(/[\s,;]+/).filter(Boolean).map(Number);
  if (!values.length || values.some((x) => !Number.isFinite(x))) throw new Error('Enter a valid list of numbers');
  return values;
};
const gcd2 = (a: number, b: number): number => { a = Math.abs(Math.trunc(a)); b = Math.abs(Math.trunc(b)); while (b) [a, b] = [b, a % b]; return a; };
const lcm2 = (a: number, b: number): number => Math.abs(a * b) / nz(gcd2(a, b), 'GCD');
const roundSig = (value: number, digits: number): number => value === 0 ? 0 : Number(value.toPrecision(Math.max(1, Math.trunc(digits))));
const decimalFraction = (x: number, maxDen = 1_000_000): [number, number] => {
  if (!Number.isFinite(x)) throw new Error('Invalid decimal');
  const sign = x < 0 ? -1 : 1; x = Math.abs(x);
  let h1=1,h0=0,k1=0,k0=1,b=x;
  do { const a=Math.floor(b); const h2=a*h1+h0; const k2=a*k1+k0; if(k2>maxDen) break; h0=h1;h1=h2;k0=k1;k1=k2; const frac=b-a; if(frac<1e-12) break; b=1/frac; } while(true);
  return [sign*h1,k1];
};
const primeFactors = (value: number): number[] => {
  let x=Math.abs(Math.trunc(value)); if(x<2) return [];
  const out:number[]=[]; for(let p=2;p*p<=x;p+=(p===2?1:2)){ while(x%p===0){out.push(p);x/=p;} } if(x>1) out.push(x); return out;
};
const generic = (id:string, intro:string, fields:CalculatorSpec['fields'], compute:CalculatorSpec['compute']):CalculatorSpec => ({id,intro,fields,compute});

const specs: Record<string, CalculatorSpec> = {};
const add = (spec: CalculatorSpec) => { specs[spec.id] = spec; };

// Math & everyday
add(generic('percentage-calculator','Calculate a percentage of a value.',[num('percentage','Percentage',20),num('value','Value',100)],v=>[result('Result',n(v,'percentage')/100*n(v,'value'))]));
add(generic('percentage-increase-calculator','Calculate the percentage increase between two values.',[num('old','Original value',100),num('current','New value',120)],v=>[result('Increase',(n(v,'current')-n(v,'old'))/nz(n(v,'old'),'Original value')*100,'%')]));
add(generic('percentage-decrease-calculator','Calculate the percentage decrease between two values.',[num('old','Original value',100),num('current','New value',80)],v=>[result('Decrease',(n(v,'old')-n(v,'current'))/nz(n(v,'old'),'Original value')*100,'%')]));
add(generic('percentage-difference-calculator','Compare two values using symmetric percentage difference.',[num('a','Value A',100),num('b','Value B',120)],v=>{const a=n(v,'a'),b=n(v,'b');return[result('Percentage difference',Math.abs(a-b)/nz((Math.abs(a)+Math.abs(b))/2,'Average magnitude')*100,'%')]}));
add(generic('reverse-percentage-calculator','Find the whole when a value represents a known percentage.',[num('part','Part value',25),num('percentage','Percentage',20)],v=>[result('Whole value',n(v,'part')/nz(n(v,'percentage')/100,'Percentage'))]));
add(generic('fraction-calculator','Add, subtract, multiply or divide two fractions.',[num('n1','Numerator 1',1,1),num('d1','Denominator 1',2,1),select('op','Operation',[{value:'+',label:'+'},{value:'-',label:'−'},{value:'*',label:'×'},{value:'/',label:'÷'}],'+'),num('n2','Numerator 2',1,1),num('d2','Denominator 2',3,1)],v=>{const a=n(v,'n1'),b=nz(n(v,'d1'),'Denominator'),c=n(v,'n2'),d=nz(n(v,'d2'),'Denominator'),op=s(v,'op');let nn:number,dd:number;if(op==='+'){nn=a*d+c*b;dd=b*d}else if(op==='-'){nn=a*d-c*b;dd=b*d}else if(op==='*'){nn=a*c;dd=b*d}else{nn=a*d;dd=b*nz(c,'Numerator 2')}const g=gcd2(nn,dd)||1;nn/=g;dd/=g;if(dd<0){nn=-nn;dd=-dd}return[result('Fraction',`${nn}/${dd}`),result('Decimal',nn/dd)]}));
add(generic('fraction-to-decimal','Convert a fraction to decimal.',[num('numerator','Numerator',1,1),num('denominator','Denominator',4,1)],v=>[result('Decimal',n(v,'numerator')/nz(n(v,'denominator'),'Denominator'))]));
add(generic('decimal-to-fraction','Convert a decimal to a reduced fraction.',[num('value','Decimal',0.75)],v=>{const [a,b]=decimalFraction(n(v,'value'));return[result('Fraction',`${a}/${b}`)]}));
add(generic('ratio-calculator','Reduce a two-part ratio.',[num('a','First value',12,1),num('b','Second value',18,1)],v=>{const a=n(v,'a'),b=n(v,'b'),g=gcd2(a,b)||1;return[result('Reduced ratio',`${a/g}:${b/g}`)]}));
add(generic('proportion-calculator','Solve a/b = c/x.',[num('a','a',2),num('b','b',3),num('c','c',4)],v=>[result('x',n(v,'b')*n(v,'c')/nz(n(v,'a'),'a'))]));
add(generic('average-calculator','Calculate the arithmetic mean.',[text('values','Numbers','10, 20, 30')],v=>{const xs=list(s(v,'values'));return[result('Average',xs.reduce((a,b)=>a+b,0)/xs.length)]}));
add(generic('weighted-average-calculator','Calculate an average using matching weights.',[text('values','Values','80, 90, 100'),text('weights','Weights','1, 2, 1')],v=>{const xs=list(s(v,'values')),ws=list(s(v,'weights'));if(xs.length!==ws.length)throw new Error('Values and weights must have the same length');const sw=ws.reduce((a,b)=>a+b,0);return[result('Weighted average',xs.reduce((a,x,i)=>a+x*(ws[i]??0),0)/nz(sw,'Weight sum'))]}));
add(generic('median-calculator','Find the middle value of a list.',[text('values','Numbers','1, 2, 3, 4, 5')],v=>{const xs=list(s(v,'values')).sort((a,b)=>a-b),m=Math.floor(xs.length/2);return[result('Median',xs.length%2?xs[m]!:((xs[m-1]??0)+(xs[m]??0))/2)]}));
add(generic('mode-calculator','Find the most frequent value or values.',[text('values','Numbers','1, 2, 2, 3')],v=>{const xs=list(s(v,'values')),m=new Map<number,number>();xs.forEach(x=>m.set(x,(m.get(x)??0)+1));const max=Math.max(...m.values());return[result('Mode',[...m.entries()].filter(([,c])=>c===max).map(([x])=>x).join(', '))]}));
add(generic('standard-deviation-calculator','Calculate population or sample standard deviation.',[text('values','Numbers','2, 4, 4, 4, 5, 5, 7, 9'),select('kind','Type',[{value:'population',label:'Population'},{value:'sample',label:'Sample'}],'population')],v=>{const xs=list(s(v,'values')),mean=xs.reduce((a,b)=>a+b,0)/xs.length,den=s(v,'kind')==='sample'?xs.length-1:xs.length;if(den<=0)throw new Error('Not enough values');return[result('Standard deviation',Math.sqrt(xs.reduce((a,x)=>a+(x-mean)**2,0)/den))]}));
add(generic('rule-of-three-calculator','Solve a proportional rule of three: a : b = c : x.',[num('a','a',2),num('b','b',4),num('c','c',3)],v=>[result('x',n(v,'b')*n(v,'c')/nz(n(v,'a'),'a'))]));
add(generic('scientific-notation-converter','Write a number in scientific notation.',[num('value','Number',123456)],v=>[result('Scientific notation',n(v,'value').toExponential())]));
add(generic('square-root-calculator','Calculate the principal square root.',[num('value','Number',144)],v=>{const x=n(v,'value');if(x<0)throw new Error('Number must be non-negative');return[result('Square root',Math.sqrt(x))]}));
add(generic('exponent-calculator','Raise a base to an exponent.',[num('base','Base',2),num('exponent','Exponent',10)],v=>[result('Result',n(v,'base')**n(v,'exponent'))]));
add(generic('logarithm-calculator','Calculate a logarithm in any positive base except 1.',[num('value','Number',100),num('base','Base',10)],v=>{const x=n(v,'value'),b=n(v,'base');if(x<=0||b<=0||b===1)throw new Error('Use a positive number and a positive base other than 1');return[result('Logarithm',Math.log(x)/Math.log(b))]}));
add(generic('factorial-calculator','Calculate n! for a non-negative integer up to 170.',[num('value','n',10,1)],v=>{const x=n(v,'value');if(!Number.isInteger(x)||x<0||x>170)throw new Error('n must be an integer from 0 to 170');let r=1;for(let i=2;i<=x;i++)r*=i;return[result('n!',r)]}));
add(generic('gcd-calculator','Find the greatest common divisor of two integers.',[num('a','a',48,1),num('b','b',18,1)],v=>[result('GCD',gcd2(n(v,'a'),n(v,'b')))]));
add(generic('lcm-calculator','Find the least common multiple of two integers.',[num('a','a',12,1),num('b','b',18,1)],v=>[result('LCM',lcm2(n(v,'a'),n(v,'b')))]));
add(generic('prime-number-checker','Check whether an integer is prime.',[num('value','Integer',97,1)],v=>{const x=Math.trunc(n(v,'value'));if(x<2)return[result('Prime?','No')];for(let i=2;i*i<=x;i++)if(x%i===0)return[result('Prime?','No')];return[result('Prime?','Yes')]}));
add(generic('prime-factorization-calculator','Factor an integer into prime factors.',[num('value','Integer',360,1)],v=>{const f=primeFactors(n(v,'value'));return[result('Prime factors',f.length?f.join(' × '):'No prime factors')]}));
add(generic('rounding-calculator','Round a number to a chosen number of decimal places.',[num('value','Number',12.34567),num('decimals','Decimal places',2,1)],v=>{const d=Math.trunc(n(v,'decimals'));if(d<0||d>15)throw new Error('Decimal places must be from 0 to 15');const p=10**d;return[result('Rounded value',Math.round((n(v,'value')+Number.EPSILON)*p)/p)]}));
add(generic('significant-figures-calculator','Round a number to significant figures.',[num('value','Number',12345.678),num('digits','Significant figures',4,1)],v=>[result('Rounded value',roundSig(n(v,'value'),n(v,'digits')))]));
add(generic('percentage-error-calculator','Calculate absolute percentage error against an accepted value.',[num('measured','Measured value',98),num('accepted','Accepted value',100)],v=>[result('Percentage error',Math.abs(n(v,'measured')-n(v,'accepted'))/Math.abs(nz(n(v,'accepted'),'Accepted value'))*100,'%')]));
add(generic('absolute-difference-calculator','Calculate the absolute difference between two values.',[num('a','Value A',10),num('b','Value B',7)],v=>[result('Absolute difference',Math.abs(n(v,'a')-n(v,'b')))]));
add(generic('range-calculator','Calculate min, max and range of a list.',[text('values','Numbers','3, 7, 2, 12, 5')],v=>{const xs=list(s(v,'values')),min=Math.min(...xs),max=Math.max(...xs);return[result('Minimum',min),result('Maximum',max),result('Range',max-min)]}));

// Business & finance
add(generic('margin-calculator','Calculate gross margin from revenue and cost.',[num('revenue','Revenue',1000),num('cost','Cost',600)],v=>[result('Margin',(n(v,'revenue')-n(v,'cost'))/nz(n(v,'revenue'),'Revenue')*100,'%')]));
add(generic('markup-calculator','Calculate markup over cost.',[num('price','Selling price',100),num('cost','Cost',60)],v=>[result('Markup',(n(v,'price')-n(v,'cost'))/nz(n(v,'cost'),'Cost')*100,'%')]));
add(generic('profit-calculator','Calculate profit from revenue and total cost.',[num('revenue','Revenue',1000),num('cost','Total cost',700)],v=>[result('Profit',n(v,'revenue')-n(v,'cost'))]));
add(generic('break-even-calculator','Calculate break-even units from fixed cost and contribution per unit.',[num('fixed','Fixed costs',10000),num('price','Price per unit',50),num('variable','Variable cost per unit',30)],v=>[result('Break-even units',Math.ceil(n(v,'fixed')/nz(n(v,'price')-n(v,'variable'),'Contribution margin')), 'units',0)]));
add(generic('roi-calculator','Calculate return on investment.',[num('gain','Final value / gain',1300),num('cost','Investment cost',1000)],v=>[result('ROI',(n(v,'gain')-n(v,'cost'))/nz(n(v,'cost'),'Investment cost')*100,'%')]));
add(generic('roas-calculator','Calculate return on advertising spend.',[num('revenue','Attributed revenue',5000),num('spend','Ad spend',1000)],v=>[result('ROAS',n(v,'revenue')/nz(n(v,'spend'),'Ad spend'),'×')]));
add(generic('cac-calculator','Calculate customer acquisition cost.',[num('marketing','Marketing cost',5000),num('sales','Sales cost',3000),num('customers','New customers',100,1)],v=>[result('CAC',(n(v,'marketing')+n(v,'sales'))/nz(n(v,'customers'),'Customers'))]));
add(generic('ltv-calculator','Estimate customer lifetime value from purchase value, frequency, margin and lifespan.',[num('purchase','Average purchase value',50),num('frequency','Purchases per year',6),num('margin','Gross margin',60),num('years','Customer lifespan (years)',3)],v=>[result('Estimated LTV',n(v,'purchase')*n(v,'frequency')*(n(v,'margin')/100)*n(v,'years'))]));
add(generic('conversion-rate-calculator','Calculate conversion rate.',[num('conversions','Conversions',50,1),num('visitors','Visitors',1000,1)],v=>[result('Conversion rate',n(v,'conversions')/nz(n(v,'visitors'),'Visitors')*100,'%')]));
add(generic('churn-rate-calculator','Calculate customer churn rate.',[num('lost','Customers lost',50,1),num('start','Customers at start',1000,1)],v=>[result('Churn rate',n(v,'lost')/nz(n(v,'start'),'Starting customers')*100,'%')]));
add(generic('growth-rate-calculator','Calculate percentage growth.',[num('start','Starting value',100),num('end','Ending value',125)],v=>[result('Growth rate',(n(v,'end')-n(v,'start'))/nz(Math.abs(n(v,'start')),'Starting value')*100,'%')]));
add(generic('cagr-calculator','Calculate compound annual growth rate.',[num('start','Starting value',1000),num('end','Ending value',1500),num('years','Years',5)],v=>{const a=n(v,'start'),b=n(v,'end'),y=n(v,'years');if(a<=0||b<0||y<=0)throw new Error('Use positive start and years');return[result('CAGR',((b/a)**(1/y)-1)*100,'%')]}));
add(generic('simple-interest-calculator','Calculate simple interest.',[num('principal','Principal',10000),num('rate','Annual rate',5),num('years','Years',3)],v=>{const p=n(v,'principal'),i=p*n(v,'rate')/100*n(v,'years');return[result('Interest',i),result('Final amount',p+i)]}));
add(generic('compound-interest-calculator','Calculate compound interest with configurable compounding frequency.',[num('principal','Principal',10000),num('rate','Annual rate',5),num('years','Years',10),num('frequency','Compounds per year',12,1)],v=>{const p=n(v,'principal'),r=n(v,'rate')/100,t=n(v,'years'),m=nz(n(v,'frequency'),'Frequency'),a=p*(1+r/m)**(m*t);return[result('Final amount',a),result('Interest',a-p)]}));
add(generic('loan-payment-calculator','Estimate fixed monthly loan payment.',[num('principal','Loan amount',250000),num('rate','Annual interest rate',5),num('years','Term (years)',30)],v=>{const p=n(v,'principal'),r=n(v,'rate')/1200,m=Math.round(n(v,'years')*12);if(m<=0)throw new Error('Term must be positive');const pay=r===0?p/m:p*r*(1+r)**m/((1+r)**m-1);return[result('Monthly payment',pay),result('Total paid',pay*m)]}));
add(generic('amortization-calculator','Calculate payment, total interest and total paid for an amortizing loan.',[num('principal','Loan amount',200000),num('rate','Annual interest rate',5),num('years','Term (years)',20)],v=>{const p=n(v,'principal'),r=n(v,'rate')/1200,m=Math.round(n(v,'years')*12);const pay=r===0?p/m:p*r*(1+r)**m/((1+r)**m-1);return[result('Monthly payment',pay),result('Total interest',pay*m-p),result('Total paid',pay*m)]}));
add(generic('savings-goal-calculator','Estimate the monthly contribution needed to reach a savings goal.',[num('goal','Goal',50000),num('current','Current savings',5000),num('rate','Annual return',4),num('years','Years',5)],v=>{const goal=n(v,'goal'),current=n(v,'current'),r=n(v,'rate')/1200,m=Math.round(n(v,'years')*12);if(m<=0)throw new Error('Years must be positive');const fvCurrent=current*(1+r)**m;const needed=goal-fvCurrent;if(needed<=0)return[result('Monthly contribution',0)];const pmt=r===0?needed/m:needed*r/((1+r)**m-1);return[result('Monthly contribution',pmt)]}));
add(generic('discount-calculator','Calculate discount amount and final price.',[num('price','Original price',100),num('discount','Discount',20)],v=>{const p=n(v,'price'),d=p*n(v,'discount')/100;return[result('Discount amount',d),result('Final price',p-d)]}));
add(generic('sale-price-calculator','Calculate a sale price after a percentage discount.',[num('price','Original price',80),num('discount','Discount',15)],v=>[result('Sale price',n(v,'price')*(1-n(v,'discount')/100))]));
add(generic('price-per-unit-calculator','Calculate unit price.',[num('price','Total price',12.99),num('quantity','Quantity',6)],v=>[result('Price per unit',n(v,'price')/nz(n(v,'quantity'),'Quantity'))]));
add(generic('cpm-calculator','Calculate advertising cost per thousand impressions.',[num('cost','Campaign cost',500),num('impressions','Impressions',100000,1)],v=>[result('CPM',n(v,'cost')/nz(n(v,'impressions'),'Impressions')*1000)]));
add(generic('cpc-calculator','Calculate cost per click.',[num('cost','Campaign cost',500),num('clicks','Clicks',1000,1)],v=>[result('CPC',n(v,'cost')/nz(n(v,'clicks'),'Clicks'))]));
add(generic('ctr-calculator','Calculate click-through rate.',[num('clicks','Clicks',1000,1),num('impressions','Impressions',100000,1)],v=>[result('CTR',n(v,'clicks')/nz(n(v,'impressions'),'Impressions')*100,'%')]));
add(generic('revenue-calculator','Calculate revenue from unit price and quantity.',[num('price','Price per unit',25),num('quantity','Units sold',100,1)],v=>[result('Revenue',n(v,'price')*n(v,'quantity'))]));
add(generic('profit-margin-calculator','Calculate profit and profit margin.',[num('revenue','Revenue',1000),num('cost','Costs',700)],v=>{const p=n(v,'revenue')-n(v,'cost');return[result('Profit',p),result('Profit margin',p/nz(n(v,'revenue'),'Revenue')*100,'%')]}));
add(generic('inventory-turnover-calculator','Calculate inventory turnover ratio.',[num('cogs','Cost of goods sold',500000),num('inventory','Average inventory',100000)],v=>[result('Inventory turnover',n(v,'cogs')/nz(n(v,'inventory'),'Average inventory'),'×')]));
add(generic('burn-rate-calculator','Calculate average monthly cash burn.',[num('start','Starting cash',500000),num('end','Ending cash',350000),num('months','Months',3)],v=>[result('Monthly burn',(n(v,'start')-n(v,'end'))/nz(n(v,'months'),'Months'))]));
add(generic('runway-calculator','Estimate runway from cash and monthly burn.',[num('cash','Cash available',250000),num('burn','Monthly burn',50000)],v=>[result('Runway',n(v,'cash')/nz(n(v,'burn'),'Monthly burn'),'months')]));
add(generic('commission-calculator','Calculate commission from sales and commission rate.',[num('sales','Sales amount',10000),num('rate','Commission rate',5)],v=>[result('Commission',n(v,'sales')*n(v,'rate')/100)]));
add(generic('unit-economics-calculator','Calculate unit revenue, unit variable cost and contribution margin.',[num('revenue','Total revenue',100000),num('variable','Total variable costs',60000),num('units','Units / customers',1000,1)],v=>{const u=nz(n(v,'units'),'Units'),r=n(v,'revenue')/u,c=n(v,'variable')/u;return[result('Revenue per unit',r),result('Variable cost per unit',c),result('Contribution per unit',r-c),result('Contribution margin',(r-c)/nz(r,'Revenue per unit')*100,'%')]}));

// Construction & DIY
const areaWaste=(id:string,intro:string)=>add(generic(id,intro,[num('length','Area length (m)',5),num('width','Area width (m)',4),num('waste','Waste allowance',10)],v=>{const area=n(v,'length')*n(v,'width'),total=area*(1+n(v,'waste')/100);return[result('Base area',area,'m²'),result('Area incl. waste',total,'m²')]}));
const volumeMass=(id:string,intro:string,density=1600)=>add(generic(id,intro,[num('length','Length (m)',5),num('width','Width (m)',3),num('depth','Depth (m)',0.1),num('density','Density (kg/m³)',density)],v=>{const vol=n(v,'length')*n(v,'width')*n(v,'depth');return[result('Volume',vol,'m³'),result('Estimated mass',vol*n(v,'density'),'kg')]}));
add(generic('concrete-calculator','Estimate concrete volume for a rectangular pour.',[num('length','Length (m)',5),num('width','Width (m)',3),num('depth','Thickness (m)',0.15),num('waste','Waste allowance',5)],v=>{const vol=n(v,'length')*n(v,'width')*n(v,'depth');return[result('Concrete volume',vol,'m³'),result('Including waste',vol*(1+n(v,'waste')/100),'m³')]}));
add(generic('cement-calculator','Estimate cement bags from concrete volume and a cement-per-volume assumption.',[num('volume','Concrete volume (m³)',1),num('cement','Cement required (kg/m³)',300),num('bag','Bag size (kg)',25)],v=>{const kg=n(v,'volume')*n(v,'cement');return[result('Cement mass',kg,'kg'),result('Bags',Math.ceil(kg/nz(n(v,'bag'),'Bag size')),'bags',0)]}));
const masonry=(id:string,label:string)=>add(generic(id,`Estimate ${label.toLowerCase()} count for a wall.`,[num('wallLength','Wall length (m)',5),num('wallHeight','Wall height (m)',2.5),num('unitLength','Unit length (m)',0.2),num('unitHeight','Unit height (m)',0.1),num('waste','Waste allowance',10)],v=>{const wall=n(v,'wallLength')*n(v,'wallHeight'),unit=n(v,'unitLength')*n(v,'unitHeight');return[result(`${label}s needed`,Math.ceil(wall/nz(unit,'Unit area')*(1+n(v,'waste')/100)),label.toLowerCase()+'s',0)]}));
masonry('brick-calculator','Brick'); masonry('concrete-block-calculator','Block');
add(generic('tile-calculator','Estimate tile count from surface and tile dimensions.',[num('length','Surface length (m)',4),num('width','Surface width (m)',3),num('tileLength','Tile length (cm)',60),num('tileWidth','Tile width (cm)',60),num('waste','Waste allowance',10)],v=>{const area=n(v,'length')*n(v,'width'),tile=n(v,'tileLength')/100*n(v,'tileWidth')/100;return[result('Surface area',area,'m²'),result('Tiles needed',Math.ceil(area/nz(tile,'Tile area')*(1+n(v,'waste')/100)),'tiles',0)]}));
areaWaste('flooring-calculator','Estimate flooring area including waste.'); areaWaste('hardwood-calculator','Estimate hardwood flooring area including waste.'); areaWaste('laminate-calculator','Estimate laminate flooring area including waste.'); areaWaste('carpet-calculator','Estimate carpet area including waste.');
add(generic('paint-calculator','Estimate paint needed for four walls of a rectangular room.',[num('length','Room length (m)',5),num('width','Room width (m)',4),num('height','Room height (m)',2.7),num('coats','Coats',2,1),num('coverage','Coverage (m²/L)',10)],v=>{const area=2*(n(v,'length')+n(v,'width'))*n(v,'height'),liters=area*n(v,'coats')/nz(n(v,'coverage'),'Coverage');return[result('Wall area',area,'m²'),result('Paint needed',liters,'L')]}));
add(generic('wallpaper-calculator','Estimate wallpaper rolls from wall area and roll coverage.',[num('length','Room length (m)',5),num('width','Room width (m)',4),num('height','Room height (m)',2.7),num('rollCoverage','Coverage per roll (m²)',5.2),num('waste','Waste allowance',10)],v=>{const area=2*(n(v,'length')+n(v,'width'))*n(v,'height')*(1+n(v,'waste')/100);return[result('Wallpaper area',area,'m²'),result('Rolls',Math.ceil(area/nz(n(v,'rollCoverage'),'Roll coverage')),'rolls',0)]}));
add(generic('drywall-calculator','Estimate drywall sheets for a wall area.',[num('length','Total wall length (m)',10),num('height','Wall height (m)',2.7),num('sheetArea','Sheet area (m²)',2.88),num('waste','Waste allowance',10)],v=>{const area=n(v,'length')*n(v,'height')*(1+n(v,'waste')/100);return[result('Wall area',area,'m²'),result('Sheets',Math.ceil(area/nz(n(v,'sheetArea'),'Sheet area')),'sheets',0)]}));
add(generic('plaster-calculator','Estimate wet plaster volume from area and thickness.',[num('area','Area (m²)',30),num('thickness','Thickness (mm)',10)],v=>[result('Plaster volume',n(v,'area')*n(v,'thickness')/1000,'m³')]));
volumeMass('gravel-calculator','Estimate gravel volume and mass.',1700); volumeMass('sand-calculator','Estimate sand volume and mass.',1600);
add(generic('mulch-calculator','Estimate mulch volume.',[num('length','Length (m)',5),num('width','Width (m)',3),num('depth','Depth (cm)',8)],v=>[result('Mulch volume',n(v,'length')*n(v,'width')*n(v,'depth')/100,'m³')]));
add(generic('soil-calculator','Estimate soil volume.',[num('length','Length (m)',5),num('width','Width (m)',3),num('depth','Depth (cm)',20)],v=>[result('Soil volume',n(v,'length')*n(v,'width')*n(v,'depth')/100,'m³')]));
volumeMass('asphalt-calculator','Estimate asphalt volume and mass.',2400);
add(generic('paver-calculator','Estimate paver count.',[num('length','Area length (m)',5),num('width','Area width (m)',4),num('paverLength','Paver length (cm)',20),num('paverWidth','Paver width (cm)',10),num('waste','Waste allowance',10)],v=>{const area=n(v,'length')*n(v,'width'),p=n(v,'paverLength')/100*n(v,'paverWidth')/100;return[result('Pavers',Math.ceil(area/nz(p,'Paver area')*(1+n(v,'waste')/100)),'pavers',0)]}));
volumeMass('stone-calculator','Estimate stone volume and mass.',2600);
add(generic('roof-pitch-calculator','Calculate roof pitch from rise and run.',[num('rise','Rise',4),num('run','Run',12)],v=>{const r=n(v,'rise'),run=nz(n(v,'run'),'Run'),ratio=r/run;return[result('Pitch angle',Math.atan(ratio)*180/Math.PI,'°'),result('Slope',ratio*100,'%'),result('Rise per 12',ratio*12,'/12')]}));
add(generic('roof-area-calculator','Estimate gable roof surface area from footprint and pitch.',[num('length','Building length (m)',10),num('width','Building width (m)',8),num('pitch','Roof pitch (degrees)',30)],v=>{const plan=n(v,'length')*n(v,'width'),cos=Math.cos(n(v,'pitch')*Math.PI/180);return[result('Roof area',plan/nz(cos,'Cosine of pitch'),'m²')]}));
add(generic('rafter-length-calculator','Calculate rafter length from horizontal run and rise.',[num('run','Horizontal run (m)',4),num('rise','Rise (m)',2)],v=>[result('Rafter length',Math.hypot(n(v,'run'),n(v,'rise')),'m')]));
add(generic('stair-calculator','Estimate stair risers and tread run.',[num('rise','Total rise (cm)',280),num('desiredRiser','Desired riser height (cm)',17.5),num('tread','Tread depth (cm)',28)],v=>{const count=Math.max(1,Math.round(n(v,'rise')/nz(n(v,'desiredRiser'),'Riser height'))),actual=n(v,'rise')/count;return[result('Number of risers',count,'',0),result('Actual riser height',actual,'cm'),result('Approx. horizontal run',(count-1)*n(v,'tread'),'cm')]}));
add(generic('deck-board-calculator','Estimate deck boards across the deck width.',[num('deckLength','Deck length (m)',6),num('deckWidth','Deck width (m)',4),num('boardWidth','Board width (mm)',140),num('gap','Gap (mm)',5)],v=>{const module=(n(v,'boardWidth')+n(v,'gap'))/1000;const count=Math.ceil(n(v,'deckWidth')/nz(module,'Board module'));return[result('Boards',count,'boards',0),result('Total board length',count*n(v,'deckLength'),'m')]}));
add(generic('deck-material-calculator','Estimate decking boards by area.',[num('length','Deck length (m)',6),num('width','Deck width (m)',4),num('boardLength','Board length (m)',3),num('boardWidth','Board width (m)',0.14),num('waste','Waste allowance',10)],v=>{const area=n(v,'length')*n(v,'width')*(1+n(v,'waste')/100),ba=n(v,'boardLength')*n(v,'boardWidth');return[result('Deck area incl. waste',area,'m²'),result('Boards',Math.ceil(area/nz(ba,'Board area')),'boards',0)]}));
add(generic('fence-calculator','Estimate fence panels and posts.',[num('length','Fence length (m)',30),num('panel','Panel width (m)',2)],v=>{const panels=Math.ceil(n(v,'length')/nz(n(v,'panel'),'Panel width'));return[result('Panels',panels,'panels',0),result('Posts',panels+1,'posts',0)]}));
add(generic('post-spacing-calculator','Calculate equal spacing between posts.',[num('length','Total length (m)',20),num('posts','Number of posts',6,1)],v=>{const p=Math.trunc(n(v,'posts'));if(p<2)throw new Error('Use at least 2 posts');return[result('Spacing',n(v,'length')/(p-1),'m')]}));
add(generic('stud-calculator','Estimate wall studs at a chosen spacing.',[num('length','Wall length (m)',5),num('spacing','Stud spacing (cm)',40)],v=>[result('Studs',Math.ceil(n(v,'length')/(nz(n(v,'spacing'),'Spacing')/100))+1,'studs',0)]));
add(generic('lumber-calculator','Estimate total lumber volume and board feet.',[num('pieces','Pieces',10,1),num('thickness','Thickness (in)',2),num('width','Width (in)',4),num('length','Length (ft)',8)],v=>{const bf=n(v,'pieces')*n(v,'thickness')*n(v,'width')*n(v,'length')/12;return[result('Board feet',bf,'bd ft')]}));
add(generic('board-foot-calculator','Calculate board feet.',[num('pieces','Pieces',1,1),num('thickness','Thickness (in)',1),num('width','Width (in)',6),num('length','Length (ft)',8)],v=>[result('Board feet',n(v,'pieces')*n(v,'thickness')*n(v,'width')*n(v,'length')/12,'bd ft')]));
add(generic('insulation-calculator','Estimate insulation packs from wall area.',[num('length','Wall length (m)',10),num('height','Wall height (m)',2.7),num('packCoverage','Coverage per pack (m²)',8),num('waste','Waste allowance',10)],v=>{const area=n(v,'length')*n(v,'height')*(1+n(v,'waste')/100);return[result('Area',area,'m²'),result('Packs',Math.ceil(area/nz(n(v,'packCoverage'),'Pack coverage')),'packs',0)]}));
add(generic('gutter-calculator','Estimate gutter sections from total gutter length.',[num('length','Required gutter length (m)',24),num('section','Section length (m)',3)],v=>[result('Sections',Math.ceil(n(v,'length')/nz(n(v,'section'),'Section length')),'sections',0)]));
add(generic('concrete-slab-calculator','Estimate concrete for a slab.',[num('length','Length (m)',6),num('width','Width (m)',4),num('thickness','Thickness (cm)',12),num('waste','Waste allowance',5)],v=>{const vol=n(v,'length')*n(v,'width')*n(v,'thickness')/100;return[result('Volume',vol,'m³'),result('Including waste',vol*(1+n(v,'waste')/100),'m³')]}));
add(generic('concrete-footing-calculator','Estimate concrete for strip footings.',[num('length','Total footing length (m)',20),num('width','Width (m)',0.5),num('depth','Depth (m)',0.3),num('waste','Waste allowance',5)],v=>{const vol=n(v,'length')*n(v,'width')*n(v,'depth');return[result('Volume',vol,'m³'),result('Including waste',vol*(1+n(v,'waste')/100),'m³')]}));
add(generic('retaining-wall-calculator','Estimate blocks for a retaining wall.',[num('length','Wall length (m)',10),num('height','Wall height (m)',1.2),num('blockLength','Block face length (cm)',40),num('blockHeight','Block face height (cm)',20),num('waste','Waste allowance',10)],v=>{const area=n(v,'length')*n(v,'height'),block=n(v,'blockLength')/100*n(v,'blockHeight')/100;return[result('Blocks',Math.ceil(area/nz(block,'Block face area')*(1+n(v,'waste')/100)),'blocks',0)]}));
volumeMass('driveway-material-calculator','Estimate driveway material volume and mass.',2200);
add(generic('pool-volume-calculator','Estimate rectangular pool volume.',[num('length','Length (m)',8),num('width','Width (m)',4),num('depth','Average depth (m)',1.5)],v=>{const vol=n(v,'length')*n(v,'width')*n(v,'depth');return[result('Volume',vol,'m³'),result('Liters',vol*1000,'L')]}));
add(generic('pond-volume-calculator','Estimate oval pond volume.',[num('length','Length (m)',5),num('width','Width (m)',3),num('depth','Average depth (m)',1)],v=>{const vol=n(v,'length')*n(v,'width')*Math.PI/4*n(v,'depth');return[result('Volume',vol,'m³'),result('Liters',vol*1000,'L')]}));
add(generic('room-area-calculator','Calculate rectangular room area.',[num('length','Room length (m)',5),num('width','Room width (m)',4)],v=>[result('Room area',n(v,'length')*n(v,'width'),'m²')]));

// Photography & creator
add(generic('dpi-calculator','Calculate dots/pixels per inch from pixels and physical size.',[num('pixels','Pixels',3000,1),num('inches','Print size (in)',10)],v=>[result('DPI',n(v,'pixels')/nz(n(v,'inches'),'Print size'),'dpi')]));
add(generic('ppi-calculator','Calculate pixels per inch.',[num('pixels','Pixels',3840,1),num('inches','Display/print width (in)',15.6)],v=>[result('PPI',n(v,'pixels')/nz(n(v,'inches'),'Size'),'ppi')]));
add(generic('print-size-calculator','Calculate print dimensions from pixel dimensions and DPI.',[num('width','Pixel width',6000,1),num('height','Pixel height',4000,1),num('dpi','DPI',300)],v=>[result('Print width',n(v,'width')/nz(n(v,'dpi'),'DPI'),'in'),result('Print height',n(v,'height')/n(v,'dpi'),'in')]));
add(generic('megapixel-calculator','Calculate image megapixels.',[num('width','Width (px)',6000,1),num('height','Height (px)',4000,1)],v=>[result('Megapixels',n(v,'width')*n(v,'height')/1_000_000,'MP')]));
add(generic('sensor-crop-factor-calculator','Calculate crop factor relative to 35 mm full frame.',[num('width','Sensor width (mm)',23.5),num('height','Sensor height (mm)',15.6)],v=>{const diag=Math.hypot(n(v,'width'),n(v,'height'));return[result('Crop factor',43.2666/nz(diag,'Sensor diagonal'),'×')]}));
add(generic('equivalent-focal-length-calculator','Calculate full-frame-equivalent focal length.',[num('focal','Focal length (mm)',35),num('crop','Crop factor',1.5)],v=>[result('Equivalent focal length',n(v,'focal')*n(v,'crop'),'mm')]));
add(generic('depth-of-field-calculator','Estimate near limit, far limit and depth of field.',[num('focal','Focal length (mm)',50),num('aperture','Aperture (f-number)',2.8),num('distance','Focus distance (m)',3),num('coc','Circle of confusion (mm)',0.03)],v=>{const f=n(v,'focal'),N=n(v,'aperture'),c=n(v,'coc'),smm=n(v,'distance')*1000,H=f*f/(nz(N,'Aperture')*nz(c,'Circle of confusion'))+f,near=H*smm/(H+smm-f),den=H-smm+f,far=den<=0?Infinity:H*smm/den;return[result('Near limit',near/1000,'m'),result('Far limit',far===Infinity?'∞':far/1000,'m'),result('Depth of field',far===Infinity?'∞':(far-near)/1000,'m')]}));
add(generic('hyperfocal-distance-calculator','Calculate hyperfocal distance.',[num('focal','Focal length (mm)',35),num('aperture','Aperture (f-number)',8),num('coc','Circle of confusion (mm)',0.03)],v=>{const f=n(v,'focal');return[result('Hyperfocal distance',(f*f/(nz(n(v,'aperture'),'Aperture')*nz(n(v,'coc'),'Circle of confusion'))+f)/1000,'m')]}));
add(generic('exposure-calculator','Calculate EV100 from aperture, shutter and ISO.',[num('aperture','Aperture (f-number)',8),num('shutter','Shutter time (seconds)',0.008),num('iso','ISO',100)],v=>{const N=n(v,'aperture'),t=nz(n(v,'shutter'),'Shutter time'),iso=nz(n(v,'iso'),'ISO');return[result('EV100',Math.log2(N*N/t)-Math.log2(iso/100),'EV')]}));
add(generic('shutter-speed-calculator','Estimate hand-holdable shutter speed using focal length and crop factor.',[num('focal','Focal length (mm)',50),num('crop','Crop factor',1)],v=>{const sec=1/nz(n(v,'focal')*n(v,'crop'),'Equivalent focal length');return[result('Suggested shutter',sec,'s'),result('Reciprocal form',`1/${Math.round(1/sec)} s`)]}));
add(generic('long-exposure-calculator','Calculate exposure time after adding an ND filter.',[num('base','Base shutter time (s)',0.008),num('stops','ND filter stops',10)],v=>[result('New shutter time',n(v,'base')*2**n(v,'stops'),'s')]));
add(generic('nd-filter-calculator','Calculate ND stops from base and target exposure times.',[num('base','Base shutter time (s)',0.008),num('target','Target shutter time (s)',8)],v=>[result('ND strength',Math.log2(n(v,'target')/nz(n(v,'base'),'Base shutter')),'stops')]));
add(generic('field-of-view-calculator','Calculate angular field of view for a sensor dimension and focal length.',[num('sensor','Sensor dimension (mm)',36),num('focal','Focal length (mm)',50)],v=>[result('Field of view',2*Math.atan(n(v,'sensor')/(2*nz(n(v,'focal'),'Focal length')))*180/Math.PI,'°')]));
add(generic('image-resolution-calculator','Calculate total pixels and megapixels.',[num('width','Width (px)',3840,1),num('height','Height (px)',2160,1)],v=>{const px=n(v,'width')*n(v,'height');return[result('Pixels',px,'px',0),result('Megapixels',px/1_000_000,'MP')]}));
add(generic('print-resolution-checker','Check effective print resolution.',[num('width','Image width (px)',6000,1),num('height','Image height (px)',4000,1),num('printWidth','Print width (in)',20),num('printHeight','Print height (in)',13.33)],v=>[result('Horizontal DPI',n(v,'width')/nz(n(v,'printWidth'),'Print width'),'dpi'),result('Vertical DPI',n(v,'height')/nz(n(v,'printHeight'),'Print height'),'dpi')]));
add(generic('aspect-ratio-calculator','Reduce width and height to an aspect ratio.',[num('width','Width',1920,1),num('height','Height',1080,1)],v=>{const w=Math.trunc(n(v,'width')),h=Math.trunc(n(v,'height')),g=gcd2(w,h)||1;return[result('Aspect ratio',`${w/g}:${h/g}`)]}));
add(generic('aspect-ratio-converter','Calculate a new height while preserving aspect ratio.',[num('width','Original width',1920),num('height','Original height',1080),num('newWidth','New width',1280)],v=>[result('New height',n(v,'newWidth')*n(v,'height')/nz(n(v,'width'),'Original width'))]));
add(generic('video-bitrate-calculator','Estimate average video bitrate from file size and duration.',[num('size','File size (MB)',1000),num('duration','Duration (seconds)',600)],v=>[result('Average bitrate',n(v,'size')*8/nz(n(v,'duration'),'Duration'),'Mbps')]));
add(generic('video-file-size-calculator','Estimate video file size from average bitrate and duration.',[num('bitrate','Bitrate (Mbps)',8),num('duration','Duration (seconds)',600)],v=>[result('Estimated file size',n(v,'bitrate')*n(v,'duration')/8,'MB')]));
add(generic('audio-file-size-calculator','Estimate audio file size from bitrate and duration.',[num('bitrate','Bitrate (kbps)',320),num('duration','Duration (seconds)',300)],v=>[result('Estimated file size',n(v,'bitrate')*n(v,'duration')/8/1000,'MB')]));
add(generic('timelapse-storage-calculator','Estimate timelapse storage.',[num('frames','Number of frames',3000,1),num('size','Average image size (MB)',25)],v=>[result('Storage',n(v,'frames')*n(v,'size')/1000,'GB')]));
add(generic('timelapse-interval-calculator','Calculate capture interval for a target timelapse duration.',[num('realDuration','Real-world duration (minutes)',120),num('videoDuration','Final video duration (seconds)',20),num('fps','Video frame rate',30)],v=>{const frames=n(v,'videoDuration')*n(v,'fps');return[result('Frames needed',frames,'frames',0),result('Capture interval',n(v,'realDuration')*60/nz(frames,'Frames'),'s')]}));
add(generic('storage-capacity-calculator','Estimate how many files fit in storage.',[num('storage','Storage (GB)',128),num('fileSize','Average file size (MB)',25)],v=>[result('Approx. files',Math.floor(n(v,'storage')*1000/nz(n(v,'fileSize'),'File size')),'files',0)]));
add(generic('raw-storage-calculator','Estimate storage required for RAW photos.',[num('photos','Number of photos',1000,1),num('size','Average RAW size (MB)',45)],v=>[result('Storage required',n(v,'photos')*n(v,'size')/1000,'GB')]));

export function getCalculatorSpec(id: string): CalculatorSpec | undefined { return specs[id]; }
export function hasCalculatorSpec(id: string): boolean { return Boolean(specs[id]); }
export function calculatorSpecCount(): number { return Object.keys(specs).length; }
export function calculatorSpecIds(): string[] { return Object.keys(specs); }
