import type { FileToolResult, FileToolSpec, FileToolValues } from '../file-types.ts';
const specs:Record<string,FileToolSpec>={};const add=(x:FileToolSpec)=>specs[x.id]=x;
const file={key:'file',label:'Image',type:'file' as const,accept:'image/*',required:true};
const out=(label:string,value:string|number,color?:string):FileToolResult=>({label,value,color});const fOut=(label:string,blob:Blob,filename:string):FileToolResult=>({kind:'file',label,blob,filename,preview:true});
const one=(v:FileToolValues)=>{const f=v.file;if(!(f instanceof File)||!f.size)throw new Error('Choose an image');return f};
async function pixels(f:File,max=256){const b=await createImageBitmap(f),scale=Math.min(1,max/Math.max(b.width,b.height)),w=Math.max(1,Math.round(b.width*scale)),h=Math.max(1,Math.round(b.height*scale)),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});if(!ctx)throw new Error('Canvas unavailable');ctx.drawImage(b,0,0,w,h);b.close();return{c,ctx,data:ctx.getImageData(0,0,w,h)}}
const hex=(r:number,g:number,b:number)=>'#'+[r,g,b].map(x=>Math.max(0,Math.min(255,Math.round(x))).toString(16).padStart(2,'0')).join('').toUpperCase();
add({id:'image-average-color',intro:'Calculate the average visible color of an image locally.',fields:[file],execute:async v=>{const {data}=await pixels(one(v));let r=0,g=0,b=0,w=0;for(let i=0;i<data.data.length;i+=4){const a=data.data[i+3]!/255;if(a<.01)continue;r+=data.data[i]!*a;g+=data.data[i+1]!*a;b+=data.data[i+2]!*a;w+=a}if(!w)throw new Error('Image has no visible pixels');const c=hex(r/w,g/w,b/w);return[out('Average color',c,c),out('RGB',`${Math.round(r/w)}, ${Math.round(g/w)}, ${Math.round(b/w)}`)]}});
add({id:'palette-from-image',intro:'Extract a compact color palette from an uploaded image.',fields:[file,{key:'colors',label:'Number of colors',type:'number',defaultValue:6,min:2,max:12,step:1}],execute:async v=>{const {data}=await pixels(one(v)),bins=new Map<string,{r:number;g:number;b:number;n:number}>();for(let i=0;i<data.data.length;i+=16){if(data.data[i+3]!<80)continue;const r=data.data[i]!,g=data.data[i+1]!,b=data.data[i+2]!,key=`${r>>5}-${g>>5}-${b>>5}`,e=bins.get(key)??{r:0,g:0,b:0,n:0};e.r+=r;e.g+=g;e.b+=b;e.n++;bins.set(key,e)}const count=Math.max(2,Math.min(12,Number(v.colors)||6)),top=[...bins.values()].sort((a,b)=>b.n-a.n).slice(0,count);return top.map((e,i)=>{const c=hex(e.r/e.n,e.g/e.n,e.b/e.n);return out(`Color ${i+1}`,c,c)})}});
add({id:'color-blindness-preview',intro:'Preview an approximate color-vision-deficiency simulation.',fields:[file,{key:'mode',label:'Simulation',type:'select',defaultValue:'deuteranopia',options:[{value:'deuteranopia',label:'Deuteranopia'},{value:'protanopia',label:'Protanopia'},{value:'tritanopia',label:'Tritanopia'}]}],execute:async v=>{const {c,ctx,data}=await pixels(one(v),1800),mats:Record<string,number[]>={deuteranopia:[.625,.375,0,.7,.3,0,0,.3,.7],protanopia:[.567,.433,0,.558,.442,0,0,.242,.758],tritanopia:[.95,.05,0,0,.433,.567,0,.475,.525]},m=mats[String(v.mode)]??mats.deuteranopia!;for(let i=0;i<data.data.length;i+=4){const r=data.data[i]!,g=data.data[i+1]!,b=data.data[i+2]!;data.data[i]=m[0]!*r+m[1]!*g+m[2]!*b;data.data[i+1]=m[3]!*r+m[4]!*g+m[5]!*b;data.data[i+2]=m[6]!*r+m[7]!*g+m[8]!*b}ctx.putImageData(data,0,0);const blob=await new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Encode failed')),'image/png'));return[fOut('Preview',blob,'color-vision-preview.png')]}});
export const colorFileToolIds=()=>Object.keys(specs);export const getColorFileSpec=(id:string)=>specs[id];
