import type { FileToolField, FileToolResult, FileToolSpec, FileToolValues } from '../file-types.ts';
const specs:Record<string,FileToolSpec>={};const add=(s:FileToolSpec)=>specs[s.id]=s;
const file=(multiple=false,accept='.pdf,application/pdf',label=multiple?'PDF files':'PDF file'):FileToolField=>({key:'file',label,type:'file',accept,multiple,required:true});
const num=(key:string,label:string,d:number,min?:number,max?:number):FileToolField=>({key,label,type:'number',defaultValue:d,min,max,step:1});
const text=(key:string,label:string,d='',area=false):FileToolField=>({key,label,type:area?'textarea':'text',defaultValue:d,rows:area?5:undefined});
const sel=(key:string,label:string,opts:{value:string;label:string}[],d?:string):FileToolField=>({key,label,type:'select',options:opts,defaultValue:d??opts[0]?.value});
const out=(label:string,value:string|number):FileToolResult=>({label,value,multiline:typeof value==='string'&&value.length>100});const fOut=(label:string,blob:Blob,filename:string,preview=false):FileToolResult=>({kind:'file',label,blob,filename,preview});
const n=(v:FileToolValues,k:string)=>Number(v[k]??0);const s=(v:FileToolValues,k:string)=>String(v[k]??'');
const one=(v:FileToolValues)=>{const f=v.file;if(!(f instanceof File)||!f.size)throw new Error('Choose a PDF file');return f};const many=(v:FileToolValues)=>Array.isArray(v.file)?v.file:(v.file instanceof File?[v.file]:[]);
const bytes=async(f:Blob)=>new Uint8Array(await f.arrayBuffer());
async function lib(){return import('@cantoo/pdf-lib')}
async function load(file:Blob,password?:string){const {PDFDocument}=await lib();return PDFDocument.load(await bytes(file),password===undefined?{}:{password})}
function ranges(input:string,max:number){const values=new Set<number>();for(const part of input.split(',').map(x=>x.trim()).filter(Boolean)){const m=part.match(/^(\d+)(?:-(\d+))?$/);if(!m)throw new Error(`Invalid page range: ${part}`);let a=Number(m[1]),b=Number(m[2]??m[1]);if(a>b)[a,b]=[b,a];for(let i=a;i<=b;i++){if(i<1||i>max)throw new Error(`Page ${i} is outside 1-${max}`);values.add(i-1)}}return[...values]}
async function save(doc:any,name='output.pdf'){const data=await doc.save({useObjectStreams:true});return fOut('PDF',new Blob([data],{type:'application/pdf'}),name)}
async function pdfjs(){const mod=await import('pdfjs-dist');try{const worker=(await import('pdfjs-dist/build/pdf.worker.min.mjs?url')).default;mod.GlobalWorkerOptions.workerSrc=worker}catch{}return mod}
async function renderPages(file:File,scale=1.5,quality=.82,gray=false){const p=await pdfjs(),doc=await p.getDocument({data:await bytes(file)}).promise,blobs:Blob[]=[];for(let i=1;i<=doc.numPages;i++){const page=await doc.getPage(i),vp=page.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas unavailable');await page.render({canvasContext:ctx,viewport:vp}).promise;if(gray){const img=ctx.getImageData(0,0,c.width,c.height),d=img.data;for(let j=0;j<d.length;j+=4){const y=Math.round(.2126*d[j]!+.7152*d[j+1]!+.0722*d[j+2]!);d[j]=d[j+1]=d[j+2]=y}ctx.putImageData(img,0,0)}const blob=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Image encode failed')),'image/jpeg',quality));blobs.push(blob)}return blobs}
async function rasterPdf(file:File,scale:number,quality:number,gray=false){const imgs=await renderPages(file,scale,quality,gray),{PDFDocument}=await lib(),doc=await PDFDocument.create();for(const img of imgs){const embedded=await doc.embedJpg(await bytes(img)),page=doc.addPage([embedded.width,embedded.height]);page.drawImage(embedded,{x:0,y:0,width:embedded.width,height:embedded.height})}return doc}
add({id:'merge-pdf',intro:'Merge multiple PDFs locally in the order selected.',fields:[file(true)],execute:async v=>{const fs=many(v);if(fs.length<2)throw new Error('Choose at least two PDF files');const {PDFDocument}=await lib(),dst=await PDFDocument.create();for(const f of fs){const src=await load(f),pages=await dst.copyPages(src,src.getPageIndices());for(const p of pages)dst.addPage(p)}return[await save(dst,'merged.pdf')]}});
add({id:'split-pdf',intro:'Split a PDF into one PDF per page.',fields:[file()],execute:async v=>{const src=await load(one(v)),{PDFDocument}=await lib(),results:FileToolResult[]=[];for(let i=0;i<src.getPageCount();i++){const dst=await PDFDocument.create(),[page]=await dst.copyPages(src,[i]);dst.addPage(page);results.push(await save(dst,`page-${i+1}.pdf`))}return results}});
add({id:'rotate-pdf',intro:'Rotate all PDF pages by a chosen angle.',fields:[file(),sel('angle','Rotation',[{value:'90',label:'90°'},{value:'180',label:'180°'},{value:'270',label:'270°'}],'90')],execute:async v=>{const doc=await load(one(v)),{degrees}=await lib(),delta=n(v,'angle');for(const page of doc.getPages())page.setRotation(degrees((page.getRotation().angle+delta)%360));return[await save(doc,'rotated.pdf')]}});
for(const [id,mode] of [['delete-pdf-pages','delete'],['extract-pdf-pages','extract']] as const)add({id,intro:`${mode==='delete'?'Delete':'Extract'} selected PDF pages.`,fields:[file(),text('pages','Pages (e.g. 1,3-5)','1')],execute:async v=>{const src=await load(one(v)),idx=ranges(s(v,'pages'),src.getPageCount()),{PDFDocument}=await lib();if(mode==='delete'){for(const i of [...idx].sort((a,b)=>b-a))src.removePage(i);return[await save(src,'pages-deleted.pdf')]}const dst=await PDFDocument.create(),copied=await dst.copyPages(src,idx);for(const p of copied)dst.addPage(p);return[await save(dst,'extracted-pages.pdf')]}});
add({id:'reorder-pdf-pages',intro:'Reorder PDF pages with a comma-separated page sequence.',fields:[file(),text('pages','New order (e.g. 3,1,2)','1')],execute:async v=>{const src=await load(one(v)),idx=s(v,'pages').split(',').map(x=>Number(x.trim())-1);if(idx.length!==src.getPageCount()||new Set(idx).size!==idx.length||idx.some(i=>i<0||i>=src.getPageCount()))throw new Error('Provide every page exactly once');const {PDFDocument}=await lib(),dst=await PDFDocument.create(),copied=await dst.copyPages(src,idx);for(const p of copied)dst.addPage(p);return[await save(dst,'reordered.pdf')]}});
async function imagesPdf(fs:File[]){const {PDFDocument}=await lib(),doc=await PDFDocument.create();for(const f of fs){let img:any;if(f.type==='image/png'||/\.png$/i.test(f.name))img=await doc.embedPng(await bytes(f));else img=await doc.embedJpg(await bytes(f));const page=doc.addPage([img.width,img.height]);page.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}return doc}
add({id:'images-to-pdf',intro:'Combine selected JPG/PNG images into one PDF.',fields:[file(true,'image/jpeg,image/png','Images')],execute:async v=>[await save(await imagesPdf(many(v)),'images.pdf')]});
for(const [id,accept] of [['jpg-to-pdf','image/jpeg,.jpg,.jpeg'],['png-to-pdf','image/png,.png']] as const)add({id,intro:'Convert selected images into a PDF.',fields:[file(true,accept,'Images')],execute:async v=>[await save(await imagesPdf(many(v)),`${id}.pdf`)]});
for(const [id,type] of [['pdf-to-jpg','image/jpeg'],['pdf-to-png','image/png']] as const)add({id,intro:`Render PDF pages as ${type.endsWith('png')?'PNG':'JPG'} images.`,fields:[file(),num('scale','Render scale ×100',150,50,400)],execute:async v=>{const p=await pdfjs(),doc=await p.getDocument({data:await bytes(one(v))}).promise,results:FileToolResult[]=[];for(let i=1;i<=doc.numPages;i++){const page=await doc.getPage(i),vp=page.getViewport({scale:n(v,'scale')/100}),c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas unavailable');await page.render({canvasContext:ctx,viewport:vp}).promise;const blob=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Encode failed')),type,.92));results.push(fOut(`Page ${i}`,blob,`page-${i}.${type.endsWith('png')?'png':'jpg'}`,true))}return results}});
add({id:'compress-pdf',intro:'Reduce PDF size by rasterizing pages with adjustable JPEG quality. Text/vector content becomes rasterized.',fields:[file(),num('quality','JPEG quality %',70,20,95),num('scale','Render scale ×100',120,50,250)],execute:async v=>{const src=one(v),doc=await rasterPdf(src,n(v,'scale')/100,n(v,'quality')/100);const result=await save(doc,'compressed.pdf');return[out('Original size',`${(src.size/1024/1024).toFixed(2)} MB`),result]}});
add({id:'add-pdf-page-numbers',intro:'Add page numbers to each page.',fields:[file(),num('fontSize','Font size',12,6,72),num('margin','Bottom margin',24,0,200)],execute:async v=>{const doc=await load(one(v)),{StandardFonts,rgb}=await lib(),font=await doc.embedFont(StandardFonts.Helvetica),size=n(v,'fontSize');doc.getPages().forEach((p:any,i:number)=>{const txt=String(i+1),w=font.widthOfTextAtSize(txt,size);p.drawText(txt,{x:(p.getWidth()-w)/2,y:n(v,'margin'),size,font,color:rgb(0,0,0)})});return[await save(doc,'numbered.pdf')]}});
add({id:'add-pdf-watermark',intro:'Add a text watermark to every page.',fields:[file(),text('watermark','Watermark','CONFIDENTIAL'),num('fontSize','Font size',48,8,200),num('opacity','Opacity %',20,1,100)],execute:async v=>{const doc=await load(one(v)),{StandardFonts,rgb,degrees}=await lib(),font=await doc.embedFont(StandardFonts.HelveticaBold),size=n(v,'fontSize');for(const p of doc.getPages()){const txt=s(v,'watermark'),w=font.widthOfTextAtSize(txt,size);p.drawText(txt,{x:(p.getWidth()-w)/2,y:p.getHeight()/2,size,font,color:rgb(.45,.45,.45),opacity:n(v,'opacity')/100,rotate:degrees(35)})}return[await save(doc,'watermarked.pdf')]}});
add({id:'remove-pdf-metadata',intro:'Clear common PDF document metadata fields.',fields:[file()],execute:async v=>{const doc=await load(one(v));doc.setTitle('');doc.setAuthor('');doc.setSubject('');doc.setKeywords([]);doc.setProducer('');doc.setCreator('');return[await save(doc,'metadata-removed.pdf')]}});
add({id:'pdf-metadata-viewer',intro:'Inspect common PDF metadata locally.',fields:[file()],execute:async v=>{const doc=await load(one(v));return[out('Metadata',JSON.stringify({title:doc.getTitle?.(),author:doc.getAuthor?.(),subject:doc.getSubject?.(),creator:doc.getCreator?.(),producer:doc.getProducer?.(),keywords:doc.getKeywords?.(),creationDate:doc.getCreationDate?.()?.toISOString?.(),modificationDate:doc.getModificationDate?.()?.toISOString?.(),pages:doc.getPageCount()},null,2))]}});
add({id:'pdf-page-count',intro:'Count pages in a PDF.',fields:[file()],execute:async v=>[out('Pages',(await load(one(v))).getPageCount())]});
add({id:'pdf-size-analyzer',intro:'Show file size and average bytes per PDF page.',fields:[file()],execute:async v=>{const f=one(v),doc=await load(f),pages=doc.getPageCount();return[out('File size',`${(f.size/1024/1024).toFixed(3)} MB`),out('Pages',pages),out('Average per page',`${(f.size/pages/1024).toFixed(1)} KB`)]}});
add({id:'crop-pdf',intro:'Set a crop box on every PDF page using point margins.',fields:[file(),num('left','Left',0,0),num('right','Right',0,0),num('top','Top',0,0),num('bottom','Bottom',0,0)],execute:async v=>{const doc=await load(one(v));for(const p of doc.getPages()){const w=p.getWidth(),h=p.getHeight(),left=n(v,'left'),right=n(v,'right'),top=n(v,'top'),bottom=n(v,'bottom');if(left+right>=w||top+bottom>=h)throw new Error('Margins exceed page size');p.setCropBox(left,bottom,w-left-right,h-top-bottom)}return[await save(doc,'cropped.pdf')]}});
add({id:'protect-pdf-with-password',intro:'Protect a PDF with AES password encryption locally.',fields:[file(),text('password','Password')],execute:async v=>{if(!s(v,'password'))throw new Error('Enter a password');const doc=await load(one(v));doc.encrypt({userPassword:s(v,'password'),ownerPassword:s(v,'password')});return[await save(doc,'protected.pdf')]}});
add({id:'unlock-pdf-with-known-password',intro:'Decrypt a PDF when you know the password and save an unencrypted copy.',fields:[file(),text('password','Known password')],execute:async v=>{const doc=await load(one(v),s(v,'password'));return[await save(doc,'unlocked.pdf')]}});
add({id:'combine-images-and-pdf',intro:'Combine PDF and JPG/PNG files into one PDF in selected order.',fields:[file(true,'.pdf,application/pdf,image/jpeg,image/png','PDF and images')],execute:async v=>{const {PDFDocument}=await lib(),dst=await PDFDocument.create();for(const f of many(v)){if(f.type==='application/pdf'||/\.pdf$/i.test(f.name)){const src=await load(f),copied=await dst.copyPages(src,src.getPageIndices());copied.forEach((p:any)=>dst.addPage(p))}else{const img=f.type==='image/png'||/\.png$/i.test(f.name)?await dst.embedPng(await bytes(f)):await dst.embedJpg(await bytes(f)),p=dst.addPage([img.width,img.height]);p.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}}return[await save(dst,'combined.pdf')]}});
add({id:'pdf-page-size-converter',intro:'Scale PDF pages to a standard page size while preserving page content.',fields:[file(),sel('size','Page size',[{value:'a4',label:'A4'},{value:'letter',label:'US Letter'},{value:'a3',label:'A3'}],'a4')],execute:async v=>{const sizes:Record<string,[number,number]>={a4:[595.28,841.89],letter:[612,792],a3:[841.89,1190.55]},[tw,th]=sizes[s(v,'size')]??sizes.a4!,src=await load(one(v)),{PDFDocument}=await lib(),dst=await PDFDocument.create();for(let i=0;i<src.getPageCount();i++){const embedded=await dst.embedPage(src.getPage(i)),scale=Math.min(tw/embedded.width,th/embedded.height),p=dst.addPage([tw,th]);p.drawPage(embedded,{x:(tw-embedded.width*scale)/2,y:(th-embedded.height*scale)/2,xScale:scale,yScale:scale})}return[await save(dst,'resized-pages.pdf')]}});
add({id:'grayscale-pdf',intro:'Create a grayscale rasterized PDF in the browser.',fields:[file(),num('scale','Render scale ×100',130,50,250),num('quality','JPEG quality %',85,20,100)],execute:async v=>[await save(await rasterPdf(one(v),n(v,'scale')/100,n(v,'quality')/100,true),'grayscale.pdf')]});
add({id:'pdf-text-extractor',intro:'Extract text from every PDF page.',fields:[file()],execute:async v=>{const p=await pdfjs(),doc=await p.getDocument({data:await bytes(one(v))}).promise,parts:string[]=[];for(let i=1;i<=doc.numPages;i++){const page=await doc.getPage(i),content=await page.getTextContent();parts.push(`--- Page ${i} ---\n${content.items.map((x:any)=>x.str??'').join(' ')}`)}return[out('Extracted text',parts.join('\n\n'))]}});
export const pdfToolIds=()=>Object.keys(specs);export const getPdfSpec=(id:string)=>specs[id];
